export type ApiResponse = Readonly<{ status: number; headers: Readonly<Record<string, string>>; body: unknown }>;
export type ApiRequest = (input: Readonly<{ token: string; method: string; path: string; headers?: Readonly<Record<string, string>>; body?: unknown }>) => Promise<ApiResponse>;
export type ProductEvent = Readonly<{ type: string; resource?: string; zone_id?: string; revision?: number }>;
export type EventSession = Readonly<{ next(resource: string, options?: Readonly<{ zoneId?: string; timeoutMs?: number }>): Promise<ProductEvent> }>;
export type MediaHandle = Readonly<{ path: string; cleanup(): Promise<void> }>;
export type FontSmokeMaterial = Readonly<{ zoneId: string; zoneRevision: number; trackId: string; catalogRevision: number; scanJobId: string; mediaPath: string; rendererRequired: false; requiredViews: readonly string[] }>;
export type FontSmokePrerequisite = Readonly<{ material: FontSmokeMaterial; cleanup(): Promise<void>; verify(): Promise<Readonly<{ restored: boolean }>> }>;
export type ProvisionInput = Readonly<{ adminToken: string; controllerToken: string; zoneId: string; rootId: string; request: ApiRequest; events: EventSession; createMedia(): Promise<MediaHandle> }>;

type RecordValue = Record<string, unknown>;
const record = (value: unknown, code: string): RecordValue => { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error(code); return Object.fromEntries(Object.entries(value)); };
const string = (value: unknown, code: string): string => { if (typeof value !== "string" || value === "") throw new Error(code); return value; };
const integer = (value: unknown, code: string): number => { const parsed = Number(value); if (!Number.isSafeInteger(parsed) || parsed < 0) throw new Error(code); return parsed; };
const array = (value: unknown, code: string): readonly unknown[] => { if (!Array.isArray(value)) throw new Error(code); return value; };
const ok = (response: ApiResponse, status: number, code: string): RecordValue => { if (response.status !== status) throw new Error(`${code}:${response.status}`); return record(response.body, code); };
const catalogTrackIds = async (request: ApiRequest, token: string): Promise<ReadonlySet<string>> => { const body = ok(await request({ token, method: "GET", path: "/api/v1/catalog/tracks?limit=500" }), 200, "CONTROL_FONT_CATALOG_PAGE_INVALID"); return new Set(array(body.tracks, "CONTROL_FONT_CATALOG_PAGE_INVALID").map((item) => string(record(item, "CONTROL_FONT_CATALOG_TRACK_INVALID").track_id, "CONTROL_FONT_CATALOG_TRACK_INVALID"))); };
const scan = async (input: ProvisionInput): Promise<Readonly<{ jobId: string; revision: number }>> => { const eventPending = input.events.next("catalog", { timeoutMs: 30_000 }); const started = ok(await input.request({ token: input.adminToken, method: "POST", path: "/api/v1/catalog/scans", body: { root_id: input.rootId } }), 202, "CONTROL_FONT_SCAN_START_FAILED"); const jobId = string(started.job_id ?? started.id, "CONTROL_FONT_SCAN_JOB_INVALID"); const event = await eventPending; if (event.type !== "invalidation" || event.resource !== "catalog") throw new Error("CONTROL_FONT_SCAN_EVENT_INVALID"); const completed = ok(await input.request({ token: input.adminToken, method: "GET", path: `/api/v1/catalog/scans/${encodeURIComponent(jobId)}` }), 200, "CONTROL_FONT_SCAN_STATUS_INVALID"); if (completed.status !== "complete") throw new Error("CONTROL_FONT_SCAN_INCOMPLETE"); return { jobId, revision: integer(completed.catalog_revision, "CONTROL_FONT_SCAN_REVISION_INVALID") }; };

export const createPcmWav = (): Uint8Array => { const sampleRate = 8_000; const samples = 800; const bytes = Buffer.alloc(44 + samples * 2); bytes.write("RIFF", 0); bytes.writeUInt32LE(bytes.length - 8, 4); bytes.write("WAVEfmt ", 8); bytes.writeUInt32LE(16, 16); bytes.writeUInt16LE(1, 20); bytes.writeUInt16LE(1, 22); bytes.writeUInt32LE(sampleRate, 24); bytes.writeUInt32LE(sampleRate * 2, 28); bytes.writeUInt16LE(2, 32); bytes.writeUInt16LE(16, 34); bytes.write("data", 36); bytes.writeUInt32LE(samples * 2, 40); for (let index = 0; index < samples; index += 1) bytes.writeInt16LE(Math.round(Math.sin(index * Math.PI / 20) * 4_000), 44 + index * 2); return bytes; };

export async function provisionControlFontSmoke(input: ProvisionInput): Promise<FontSmokePrerequisite> {
  const baselineStatus = ok(await input.request({ token: input.controllerToken, method: "GET", path: "/api/v1/catalog/status" }), 200, "CONTROL_FONT_CATALOG_BASELINE_INVALID"); const baselineCount = integer(baselineStatus.track_count, "CONTROL_FONT_CATALOG_BASELINE_INVALID"); const baselineTracks = await catalogTrackIds(input.request, input.controllerToken); const baselineZones = ok(await input.request({ token: input.adminToken, method: "GET", path: "/api/v1/zones" }), 200, "CONTROL_FONT_ZONES_BASELINE_INVALID"); if (array(baselineZones.zones, "CONTROL_FONT_ZONES_BASELINE_INVALID").some((item) => record(item, "CONTROL_FONT_ZONE_INVALID").zone_id === input.zoneId)) throw new Error("CONTROL_FONT_ZONE_COLLISION");
  const media = await input.createMedia(); let zoneCreated = false; let cleaned = false; let material: FontSmokeMaterial | undefined;
  const cleanup = async (): Promise<void> => { if (cleaned) return; if (zoneCreated) { const state = ok(await input.request({ token: input.controllerToken, method: "GET", path: `/api/v1/zones/${encodeURIComponent(input.zoneId)}/playback-state` }), 200, "CONTROL_FONT_ZONE_STATE_INVALID"); const revision = integer(state.revision, "CONTROL_FONT_ZONE_STATE_INVALID"); const eventPending = input.events.next("zones", { zoneId: input.zoneId, timeoutMs: 30_000 }); ok(await input.request({ token: input.adminToken, method: "DELETE", path: `/api/v1/zones/${encodeURIComponent(input.zoneId)}`, headers: { "if-match": `"${revision}"`, "idempotency-key": `control-font-delete-${input.zoneId}` } }), 200, "CONTROL_FONT_ZONE_DELETE_FAILED"); const event = await eventPending; if (event.type !== "invalidation" || event.resource !== "zones" || event.zone_id !== input.zoneId) throw new Error("CONTROL_FONT_ZONE_DELETE_EVENT_INVALID"); zoneCreated = false; } await media.cleanup(); await scan(input); const tracks = await catalogTrackIds(input.request, input.controllerToken); const status = ok(await input.request({ token: input.controllerToken, method: "GET", path: "/api/v1/catalog/status" }), 200, "CONTROL_FONT_CATALOG_RESTORE_INVALID"); if (integer(status.track_count, "CONTROL_FONT_CATALOG_RESTORE_INVALID") !== baselineCount || [...tracks].some((id) => !baselineTracks.has(id))) throw new Error("CONTROL_FONT_CATALOG_NOT_RESTORED"); cleaned = true; };
  try { const scanned = await scan(input); const tracks = await catalogTrackIds(input.request, input.controllerToken); const added = [...tracks].filter((id) => !baselineTracks.has(id)); if (added.length !== 1) throw new Error("CONTROL_FONT_TRACK_ID_NOT_UNIQUE"); const zoneEvent = input.events.next("zones", { timeoutMs: 30_000 }); const zone = ok(await input.request({ token: input.adminToken, method: "POST", path: "/api/v1/zones", body: { zone_id: input.zoneId, name: "Korean font smoke" } }), 201, "CONTROL_FONT_ZONE_CREATE_FAILED"); zoneCreated = true; const observedZone = await zoneEvent; if (observedZone.type !== "invalidation" || observedZone.resource !== "zones") throw new Error("CONTROL_FONT_ZONE_CREATE_EVENT_INVALID"); const zoneRevision = integer(zone.revision, "CONTROL_FONT_ZONE_REVISION_INVALID"); const views = ["queue", "automatic-preview", "decision-explanation", "continuation-policy"] as const; for (const view of views) ok(await input.request({ token: input.controllerToken, method: "GET", path: `/api/v1/zones/${encodeURIComponent(input.zoneId)}/${view}` }), 200, `CONTROL_FONT_VIEW_UNAVAILABLE:${view}`); material = { zoneId: input.zoneId, zoneRevision, trackId: added[0]!, catalogRevision: scanned.revision, scanJobId: scanned.jobId, mediaPath: media.path, rendererRequired: false, requiredViews: ["catalog/status", "queue", "automatic-preview", "decision-explanation", "continuation-policy", "zones", "playback-state", "catalog/tracks", "event snapshot"] }; return { material, cleanup, verify: async () => ({ restored: cleaned }) }; } catch (error) { try { await cleanup(); } catch (cleanupError) { throw new AggregateError([error, cleanupError], "CONTROL_FONT_PROVISION_AND_CLEANUP_FAILED"); } throw error; }
}
