/// <reference path="../../../packaging/control/node_modules/@types/bun/index.d.ts" />
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, test } from "bun:test";
import { createPcmWav, provisionControlFontSmoke, type ApiRequest, type ProductEvent } from "./control-font-smoke-prerequisite";

const fixture = () => {
  let media = false; let zone: Readonly<{ zone_id: string; revision: number }> | undefined; let generation = 0; const operations: string[] = []; const waiters = new Map<string, (event: ProductEvent) => void>();
  const events = { next: (resource: string, options: Readonly<{ zoneId?: string }> = {}) => new Promise<ProductEvent>((resolveEvent) => waiters.set(`${resource}:${options.zoneId ?? ""}`, resolveEvent)) };
  const reply = (status: number, body: unknown, headers: Readonly<Record<string, string>> = {}): Readonly<{ status: number; headers: Readonly<Record<string, string>>; body: unknown }> => ({ status, headers, body });
  const request: ApiRequest = async ({ method, path, body }) => { operations.push(`${method} ${path}`); if (method === "GET" && path === "/api/v1/catalog/status") return reply(200, { catalog_revision: generation, track_count: media ? 1 : 0 }); if (method === "GET" && path === "/api/v1/catalog/tracks?limit=500") return reply(200, { catalog_revision: generation, tracks: media ? [{ track_id: "track-observed" }] : [] }); if (method === "POST" && path === "/api/v1/catalog/scans") { generation += 1; waiters.get("catalog:")?.({ type: "invalidation", resource: "catalog", revision: generation }); return reply(202, { job_id: `scan-${generation}` }); } if (method === "GET" && path.startsWith("/api/v1/catalog/scans/")) return reply(200, { status: "complete", catalog_revision: generation }); if (method === "GET" && path === "/api/v1/zones") return reply(200, { zones: zone === undefined ? [] : [zone] }); if (method === "POST" && path === "/api/v1/zones") { const zoneId = (body as { zone_id: string }).zone_id; zone = { zone_id: zoneId, revision: 0 }; waiters.get("zones:")?.({ type: "invalidation", resource: "zones", revision: 0 }); return reply(201, zone, { etag: '"0"' }); } if (method === "GET" && path.endsWith("/playback-state")) return reply(200, { zone_id: zone?.zone_id, revision: zone?.revision ?? 0 }, { etag: `"${zone?.revision ?? 0}"` }); if (method === "DELETE" && path.startsWith("/api/v1/zones/")) { const id = zone?.zone_id ?? ""; zone = undefined; waiters.get(`zones:${id}`)?.({ type: "invalidation", resource: "zones", zone_id: id, revision: 1 }); return reply(200, { zone_id: id, revision: 1 }, { etag: '"1"' }); } if (method === "GET" && ["queue", "automatic-preview", "decision-explanation", "continuation-policy"].some((name) => path.endsWith(`/${name}`))) return reply(200, { revision: 0 }); throw new Error(`UNHANDLED:${method}:${path}`); };
  return { request, events, operations, createMedia: async () => { media = true; return { path: "/task/catalog/korean-font-smoke.wav", cleanup: async () => { media = false; } }; }, state: () => ({ media, zone }) };
};

describe("Control Korean font smoke prerequisite", () => {
  test("creates valid PCM WAV material and reverses catalog and zone state", async () => { const backend = fixture(); const wav = createPcmWav(); expect(Buffer.from(wav.subarray(0, 4)).toString()).toBe("RIFF"); expect(Buffer.from(wav.subarray(8, 12)).toString()).toBe("WAVE"); expect(wav.byteLength).toBe(1644); const handle = await provisionControlFontSmoke({ adminToken: "admin", controllerToken: "controller", zoneId: "font-smoke", rootId: "default", request: backend.request, events: backend.events, createMedia: backend.createMedia }); expect(handle.material).toMatchObject({ zoneId: "font-smoke", trackId: "track-observed", rendererRequired: false }); expect(handle.material.requiredViews).toContain("automatic-preview"); await handle.cleanup(); expect(await handle.verify()).toEqual({ restored: true }); expect(backend.state()).toEqual({ media: false, zone: undefined }); expect(backend.operations).toContain("DELETE /api/v1/zones/font-smoke"); });
  test("maps the shipped policy label through every render and activation dependency", () => { const repository = resolve(import.meta.dirname, "../../.."); const behavior = readFileSync(resolve(repository, "apps/control/lib/behavior_model.dart"), "utf8"); const panel = readFileSync(resolve(repository, "apps/control/lib/policy_panel.dart"), "utf8"); const home = readFileSync(resolve(repository, "apps/control/lib/control_home_view.dart"), "utf8"); const pairing = readFileSync(resolve(repository, "apps/control/lib/control_app_pairing.dart"), "utf8"); expect(behavior).toContain("Policy.stop => '재생 종료'"); expect(panel).toContain("Policy.values"); expect(panel).toContain("ChoiceChip"); for (const gate of ["gateway != null", "catalog != null", "queue != null", "preview != null", "decision != null"]) expect(home).toContain(gate); for (const load of ["connected.policy()", "connected.catalog()", "connected.queue()", "connected.preview()", "connected.explanation()", "connected.subscribe()", "connected.zones()", "loadedSession.watchZones({loadedZone})", "connected.playbackState(loadedZone)", "connected.browseCatalog(limit: 100)"]) expect(pairing).toContain(load); });
});
