#!/usr/bin/env node
import { createHash } from "node:crypto";
import { mkdir, readFile, utimes, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, relative, resolve, sep } from "node:path";
import { findUnsafeEvidence } from "../receipt-redaction.mjs";
import { createProductionHarness } from "./installed-product-harness.mjs";

const SCENARIOS = ["pair", "admin", "settings-restart", "multi-root-scan", "browse-search", "secure-token-restart", "queue-add", "queue-reorder", "queue-remove", "queue-clear", "queue-retry", "queue-skip", "transport-start", "transport-pause", "transport-resume", "transport-stop", "transport-skip", "transport-seek", "transport-next", "transport-previous", "policy", "event-gap-resync", "renderer-assignment-status", "invalid-config", "stale-revision", "certificate-change", "unavailable-explicit-head", "offline-renderer", "interrupted-restart", "revocation"];
const PROBES = ["malformed-input", "stale-state", "dirty-worktree", "hung-command", "flaky-test", "misleading-output", "repeated-interruption"];
const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");
const safe = (value) => { const issue = findUnsafeEvidence(value); if (issue !== undefined) throw new Error(`TASK19_EVIDENCE_REDACTION_FAILED:${issue.code}:${issue.path}`); return value; };
const timestamp = (value, code) => { const parsed = Date.parse(value); if (!Number.isFinite(parsed)) throw new Error(code); return parsed; };
const nativeAdapter = (backend) => { const harness = createProductionHarness(backend); const invoke = (operation, input) => harness.execute(operation, input); return {
  inventory: (input) => invoke("inventory", input), start: (input) => invoke("start", input), scenario: (input) => invoke("scenario", input), performance: (input) => invoke("performance", input), probe: (input) => invoke("probe", input), terminate: (input) => invoke("terminate", input),
}; };
const referencePath = (root, path) => { const value = relative(root, path); if (value === "" || value === ".." || value.startsWith(`..${sep}`) || isAbsolute(value)) throw new Error("TASK19_OUTPUT_OUTSIDE_EVIDENCE_ROOT"); return value.replaceAll("\\", "/"); };
const writeJson = async (root, output, name, value, observedAt) => { safe(value); const path = resolve(output, name); const relativePath = referencePath(root, path); await mkdir(dirname(path), { recursive: true }); const bytes = Buffer.from(`${JSON.stringify(value, null, 2)}\n`); await writeFile(path, bytes, { mode: 0o400, flag: "wx" }); if (observedAt !== undefined) { const at = new Date(observedAt); await utimes(path, at, at); } return { path: relativePath, sha256: sha256(bytes) }; };
const roleOrder = (run) => { const byRole = new Map(run.processes.map((process) => [process.role, process])); const server = byRole.get("server"); const control = byRole.get(`control-${run.platform}`); const renderer = byRole.get("renderer"); if (!server || !control || !renderer) throw new Error("TASK19_PROCESS_PLAN_INVALID"); return run.startupOrder === "server_first" ? [server, renderer, control] : [control, server, renderer]; };
const inventory = (value, code) => { safe(value); timestamp(value?.capturedAt, code); if (!Array.isArray(value?.resources) || value.resources.some((item) => typeof item?.type !== "string" || typeof item.id !== "string" || typeof item.observedBy !== "string" || item.observedBy === "os-enumerator")) throw new Error(code); return value; };
const assertCaptureOrder = (raw) => { const values = [raw.before?.capture, raw.request?.capture, raw.response?.capture, raw.event?.capture, raw.after?.capture]; const [before, request, response, event, after] = values.map((value) => timestamp(value?.capturedAt, "TASK19_CAPTURE_TIMESTAMP_INVALID")); if (!(before < request && request < response && request < event && response < after && event < after)) throw new Error("TASK19_CAPTURE_ORDER_INVALID"); for (const capture of values) safe(capture); };
const processObservation = (raw, expected, plan) => { const artifact = plan.files[expected.packageKey]; if (!artifact || raw?.role !== expected.role || raw.packagePath !== expected.packagePath || raw.packageSha256 !== artifact.sha256 || JSON.stringify(raw.installCommand) !== JSON.stringify(expected.installCommand) || raw.packageArgumentIndex !== expected.packageArgumentIndex || raw.installCommand[raw.packageArgumentIndex] !== raw.packagePath || JSON.stringify(raw.launchCommand) !== JSON.stringify(expected.launchCommand) || typeof raw.id !== "string" || !Number.isInteger(raw.pid) || raw.pid < 1) throw new Error("TASK19_PROCESS_OBSERVATION_INVALID"); timestamp(raw.startedAt, "TASK19_PROCESS_OBSERVATION_INVALID"); return safe(raw); };
const captureScenario = async (root, output, runId, raw) => { assertCaptureOrder(raw); const prefix = `${runId}/${raw.id}`; const before = await writeJson(root, output, `${prefix}-before.json`, raw.before.capture, raw.before.capture.capturedAt); const request = await writeJson(root, output, `${prefix}-request.json`, raw.request.capture, raw.request.capture.capturedAt); const response = await writeJson(root, output, `${prefix}-response.json`, raw.response.capture, raw.response.capture.capturedAt); const event = await writeJson(root, output, `${prefix}-event.json`, raw.event.capture, raw.event.capture.capturedAt); const after = await writeJson(root, output, `${prefix}-after.json`, raw.after.capture, raw.after.capture.capturedAt); return { id: raw.id, material: raw.material, request: { processId: raw.request.processId, sequence: raw.request.sequence, method: raw.request.method, target: raw.request.target, body: request }, response: { status: raw.response.status, code: raw.response.code, body: response }, event: { sequence: raw.event.sequence, type: raw.event.type, stateRevision: raw.event.stateRevision, body: event }, before: { revision: raw.before.revision, snapshot: before }, after: { revision: raw.after.revision, snapshot: after } }; };

export class Task19CleanupError extends Error { constructor(failures, postInventory, cause) { super("TASK19_CLEANUP_AGGREGATE_FAILED"); this.name = "Task19CleanupError"; this.failures = failures; this.postInventory = postInventory; this.cause = cause; } }

export const executeInstalledScenarios = async ({ plan, evidenceRoot, output, adapter: requestedAdapter, harnessBackend, clock = () => new Date().toISOString() }) => {
  if (plan?.schemaVersion !== 2 || plan.kind !== "task19_trusted_execution_plan" || plan.qualificationReady !== true || plan.scenarioCount !== SCENARIOS.length || plan.probeCount !== PROBES.length || !plan.receipt || !Array.isArray(plan.runs)) throw new Error("TASK19_TRUSTED_PLAN_INVALID");
  const root = resolve(evidenceRoot ?? output); const destination = resolve(output); referencePath(root, resolve(destination, ".root-check"));
  if (requestedAdapter === undefined) { for (const [key, code] of [["harness", "TASK19_SCENARIO_HARNESS_DIGEST_MISMATCH"], ["scenarioContract", "TASK19_SCENARIO_CONTRACT_DIGEST_MISMATCH"], ["scenarioProvisioner", "TASK19_SCENARIO_PROVISIONER_DIGEST_MISMATCH"], ["nativeCapture", "TASK19_NATIVE_CAPTURE_DIGEST_MISMATCH"], ["webOrigin", "TASK19_WEB_ORIGIN_DIGEST_MISMATCH"], ["tlsIdentityGenerator", "TASK19_TLS_IDENTITY_GENERATOR_DIGEST_MISMATCH"], ["operationAdapter", "TASK19_OPERATION_ADAPTER_DIGEST_MISMATCH"], ["inventoryAdapter", "TASK19_INVENTORY_ADAPTER_DIGEST_MISMATCH"], ["processAdapter", "TASK19_PROCESS_ADAPTER_DIGEST_MISMATCH"]]) { const path = plan.driver[`${key}Path`]; const digest = plan.driver[`${key}Sha256`]; if (typeof path !== "string" || sha256(await readFile(resolve(path))) !== digest) throw new Error(code); } }
  const adapter = requestedAdapter ?? nativeAdapter(harnessBackend); const runReferences = []; let liveRun;
  const finishRun = async ({ run, beforeObservation, allocatedObservation, owned, scenarios, primaryFailure }) => { const cleanupFailures = []; const ended = new Map(); const descendants = primaryFailure?.descendants ?? []; for (const process of [...owned].reverse()) { try { const observation = safe(await adapter.terminate({ id: process.id, pid: process.pid, role: process.role, descendants })); timestamp(observation?.endedAt, "TASK19_PROCESS_TERMINATION_OBSERVATION_INVALID"); if (!Number.isInteger(observation.exitCode)) throw new Error("TASK19_PROCESS_TERMINATION_OBSERVATION_INVALID"); ended.set(process.id, observation); } catch (error) { cleanupFailures.push({ operation: "terminate", processId: process.id, message: error instanceof Error ? error.message : String(error) }); } } let afterObservation; try { afterObservation = inventory(await adapter.inventory({ runId: run.runId, phase: "after" }), "TASK19_INVENTORY_INVALID"); } catch (error) { cleanupFailures.push({ operation: "post-inventory", message: error instanceof Error ? error.message : String(error) }); } if (afterObservation && JSON.stringify(beforeObservation.resources) !== JSON.stringify(afterObservation.resources)) cleanupFailures.push({ operation: "post-state", message: "TASK19_CLEANUP_POST_STATE_FAILED" }); if (cleanupFailures.length) throw new Task19CleanupError(cleanupFailures, afterObservation, primaryFailure); if (primaryFailure !== undefined) throw primaryFailure; const recordedAt = clock(); const processes = owned.map((process) => ({ ...process, ...ended.get(process.id) })); const tlsPlan = { capture: processes.find((process) => process.role === "server")?.tlsBinding, web: processes.find((process) => process.role === "control-web")?.tlsBinding }; const transcript = { schemaVersion: 2, kind: "installed_product_run_transcript", recordedAt, runId: run.runId, platform: run.platform, startupOrder: run.startupOrder, artifactSetSha256: plan.receipt.bindings.artifactSetSha256, tlsPlan, processes, inventories: { before: beforeObservation.resources, allocated: allocatedObservation.resources, after: afterObservation.resources }, scenarios }; return { runId: run.runId, platform: run.platform, startupOrder: run.startupOrder, ...(await writeJson(root, destination, `${run.runId}.transcript.json`, transcript, recordedAt)) }; };
  for (const run of plan.runs) {
    const beforeObservation = inventory(await adapter.inventory({ runId: run.runId, phase: "before" }), "TASK19_INVENTORY_INVALID"); const owned = []; const scenarios = []; let allocatedObservation; let primaryFailure;
    try {
      for (const expected of roleOrder(run)) { const raw = processObservation(await adapter.start({ runId: run.runId, role: expected.role, process: expected, packageSha256: plan.files[expected.packageKey].sha256 }), expected, plan); owned.push(raw); }
      allocatedObservation = inventory(await adapter.inventory({ runId: run.runId, phase: "allocated" }), "TASK19_INVENTORY_INVALID");
      const control = owned.find((process) => process.role === `control-${run.platform}`); if (!control) throw new Error("TASK19_CONTROL_PROCESS_MISSING");
      for (const id of SCENARIOS) { const raw = await adapter.scenario({ runId: run.runId, id, processId: control.id }); if (raw?.id !== id) throw new Error("TASK19_SCENARIO_BINDING_INVALID"); scenarios.push(await captureScenario(root, destination, run.runId, raw)); }
    } catch (error) { primaryFailure = error; }
    const state = { run, beforeObservation, allocatedObservation, owned, scenarios, primaryFailure }; if (run === plan.runs.at(-1) && primaryFailure === undefined) liveRun = state; else runReferences.push(await finishRun(state));
  }
  if (liveRun === undefined) throw new Error("TASK19_LIVE_RUN_REQUIRED"); let liveFinished = false; try { const runIds = plan.runs.map(({ runId }) => runId); const rawPerformance = safe(await adapter.performance({ runIds })); const performanceAt = rawPerformance.recordedAt; timestamp(performanceAt, "TASK19_PERFORMANCE_OBSERVATION_INVALID");
  const performance = await writeJson(root, destination, "performance.transcript.json", { schemaVersion: 2, kind: "installed_product_performance_transcript", artifactSetSha256: plan.receipt.bindings.artifactSetSha256, ...rawPerformance, runIds }, performanceAt);
  const records = [];
  for (const [index, id] of PROBES.entries()) { const runId = liveRun.run.runId; const raw = safe(await adapter.probe({ runId, id })); const started = timestamp(raw?.startedAt, "TASK19_PROBE_WINDOW_INVALID"); const stdoutAt = timestamp(raw?.stdout?.capturedAt, "TASK19_PROBE_WINDOW_INVALID"); const stderrAt = timestamp(raw?.stderr?.capturedAt, "TASK19_PROBE_WINDOW_INVALID"); const ended = timestamp(raw?.endedAt, "TASK19_PROBE_WINDOW_INVALID"); if (raw.id !== id || raw.runId !== runId || !Number.isInteger(raw.exitCode) || raw.exitCode === 0 || !(started < stdoutAt && stdoutAt < stderrAt && stderrAt < ended)) throw new Error("TASK19_PROBE_WINDOW_INVALID"); const stdout = await writeJson(root, destination, `probe-${id}-stdout.json`, raw.stdout, raw.stdout.capturedAt); const stderr = await writeJson(root, destination, `probe-${id}-stderr.json`, raw.stderr, raw.stderr.capturedAt); records.push({ id, runId, command: raw.command, startedAt: raw.startedAt, endedAt: raw.endedAt, exitCode: raw.exitCode, stdout, stderr }); }
  const probesAt = clock(); const probes = await writeJson(root, destination, "probes.transcript.json", { schemaVersion: 2, kind: "installed_product_probe_transcript", recordedAt: probesAt, artifactSetSha256: plan.receipt.bindings.artifactSetSha256, records }, probesAt); liveFinished = true; runReferences.push(await finishRun(liveRun)); const recordedAt = clock();
  return { schemaVersion: 1, kind: "task19_protected_execution", evidenceRoot: ".", productCommandsExecuted: plan.runs.length * 3, installedProductReceipt: { schemaVersion: 3, kind: "installed_server_control_e2e", recordedAt, runId: "task19-installed-product", ...plan.receipt, runs: runReferences, performance, probes } }; } finally { if (!liveFinished) await finishRun(liveRun); }
};

if (process.argv[1] && resolve(process.argv[1]) === new URL(import.meta.url).pathname) { const args = process.argv.slice(2); if (args.length !== 4 || args[0] !== "--plan" || args[2] !== "--output") throw new Error("TASK19_SCENARIO_RUNTIME_USAGE"); const plan = JSON.parse(await readFile(resolve(args[1]), "utf8")); const outputPath = resolve(args[3]); const result = await executeInstalledScenarios({ plan, evidenceRoot: dirname(outputPath), output: dirname(outputPath) }); await writeFile(outputPath, `${JSON.stringify(result, null, 2)}\n`, { mode: 0o400, flag: "wx" }); }
