import { describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { createTask19FrameController } from "./task19-frame-controller.mjs";
const wire = (text) => { const payload = Buffer.from(text); return { payload, bytes: Buffer.concat([Buffer.from([0x81, payload.length]), payload]) }; };
const metadata = ({ epoch = "7", sequence, kind = "invalidation", resource = "queue", zoneId = "main", revision = sequence }) => ({ epoch, sequence: String(sequence), kind, resource: kind === "invalidation" ? resource : null, zoneId: kind === "invalidation" ? zoneId : null, revision: kind === "invalidation" ? String(revision) : null });
const observe = (controller, text, value) => { const encoded = wire(text); const result = controller.observe({ ...encoded, metadata: value }); return { ...encoded, ...result }; };
const plan = (runId, observedFrame, overrides = {}) => Object.freeze({ runId, ...observedFrame, ...overrides });
const sha = (bytes) => createHash("sha256").update(bytes).digest("hex");

describe("Task19 run-scoped event frame controller", () => {
  test("preserves original frame and payload bytes without JSON reserialization", () => { const controller = createTask19FrameController({ runId: "run-a" }); const text = '{ "type" : "invalidation", "server_epoch" : 7, "sequence" : 1, "resource" : "queue", "revision" : 1 }'; const observed = observe(controller, text, metadata({ sequence: 1 })); const replayed = controller.replay(plan("run-a", observed.observedFrame)); expect(replayed).toEqual(observed.bytes); expect(sha(replayed)).toBe(observed.observedFrame.frameHash); expect(observed.observedFrame.payloadHash).toBe(sha(observed.payload)); expect(replayed).not.toEqual(wire(JSON.stringify(JSON.parse(text))).bytes); const replay = controller.diagnostics().find(({ kind }) => kind === "replay"); expect(replay).toMatchObject({ inputSha256: observed.observedFrame.frameHash, outputSha256: observed.observedFrame.frameHash }); });
  test("retains snapshot and invalidation collisions as distinct exact identities", () => { const controller = createTask19FrameController({ runId: "run-a" }); const invalidation = observe(controller, '{"type":"invalidation","server_epoch":7,"sequence":9,"resource":"queue","revision":9}', metadata({ sequence: 9 })); const snapshot = observe(controller, '{"type":"snapshot","server_epoch":7,"sequence":9,"resources":[]}', metadata({ sequence: 9, kind: "snapshot" })); expect(invalidation.observedFrame.frameId).not.toBe(snapshot.observedFrame.frameId); expect(() => controller.select({ epoch: "7", sequence: "9" })).toThrow("TASK19_FRAME_SELECTOR_AMBIGUOUS"); expect(controller.select({ epoch: "7", sequence: "9", kind: "snapshot", resource: null })).toEqual(snapshot.observedFrame); expect(controller.replay(plan("run-a", invalidation.observedFrame))).toEqual(invalidation.bytes); expect(controller.replay(plan("run-a", snapshot.observedFrame))).toEqual(snapshot.bytes); });
  test("preserves exact uint64 epoch sequence and revision lexemes", () => { const controller = createTask19FrameController({ runId: "run-a" }); const max = "18446744073709551615"; const observed = observe(controller, `{"type":"invalidation","server_epoch":${max},"sequence":${max},"resource":"catalog","revision":${max}}`, metadata({ epoch: max, sequence: max, resource: "catalog", revision: max })); expect(observed.observedFrame).toMatchObject({ epoch: max, sequence: max, revision: max, kind: "invalidation", resource: "catalog" }); expect(controller.replay(plan("run-a", observed.observedFrame))).toEqual(observed.bytes); });
  test("rejects unknown, cross-run, mutable, ambiguous, metadata-drift, and hash-drift plans", () => { const controller = createTask19FrameController({ runId: "run-a" }); const observed = observe(controller, '{"type":"invalidation","server_epoch":7,"sequence":1,"resource":"queue","revision":1}', metadata({ sequence: 1 })); expect(() => controller.replay({ runId: "run-a", ...observed.observedFrame })).toThrow("TASK19_FRAME_PLAN_INVALID"); expect(() => controller.replay(plan("run-b", observed.observedFrame))).toThrow("TASK19_FRAME_CROSS_RUN"); expect(() => controller.replay(plan("run-a", observed.observedFrame, { kind: "snapshot" }))).toThrow("TASK19_FRAME_METADATA_DRIFT"); expect(() => controller.replay(plan("run-a", observed.observedFrame, { frameHash: "0".repeat(64) }))).toThrow("TASK19_FRAME_HASH_MISMATCH"); expect(() => controller.replay(plan("run-a", { ...observed.observedFrame, frameId: `frame:${"f".repeat(64)}`, frameHash: "f".repeat(64) }))).toThrow("TASK19_FRAME_REPLAY_UNOBSERVED"); expect(() => controller.select({ epoch: "7" })).toThrow("TASK19_FRAME_SELECTOR_INVALID"); controller.cleanup(); expect(() => controller.replay(plan("run-a", observed.observedFrame))).toThrow("TASK19_FRAME_CONTROLLER_CLOSED"); });
  test("drops only a repeated frame matching an already observed immutable identity", () => { const controller = createTask19FrameController({ runId: "run-a" }); const text = '{"type":"invalidation","server_epoch":7,"sequence":2,"resource":"queue","revision":2}'; const first = observe(controller, text, metadata({ sequence: 2 })); controller.armDrop(plan("run-a", first.observedFrame)); const repeated = observe(controller, text, metadata({ sequence: 2 })); expect(repeated.forward).toBe(false); expect(controller.diagnostics().find(({ kind }) => kind === "drop")).toMatchObject({ observedFrame: first.observedFrame, inputSha256: first.observedFrame.frameHash }); });
  test("drops the next matching physical frame from an observed anchor", () => { const controller = createTask19FrameController({ runId: "run-a" }); const anchor = observe(controller, '{"type":"invalidation","server_epoch":7,"sequence":2,"resource":"queue","zone_id":"main","revision":2}', metadata({ sequence: 2 })); controller.armDrop(plan("run-a", anchor.observedFrame, { relation: "next" })); const unrelated = observe(controller, '{"type":"invalidation","server_epoch":7,"sequence":3,"resource":"catalog","revision":3}', metadata({ sequence: 3, resource: "catalog" })); expect(unrelated.forward).toBe(true); const wrongZone = observe(controller, '{"type":"invalidation","server_epoch":7,"sequence":3,"resource":"queue","zone_id":"office","revision":3}', metadata({ sequence: 3, zoneId: "office" })); expect(wrongZone.forward).toBe(true); const next = observe(controller, '{"type":"invalidation","server_epoch":7,"sequence":3,"resource":"queue","zone_id":"main","revision":3}', metadata({ sequence: 3 })); expect(next.forward).toBe(false); expect(controller.diagnostics().find(({ kind }) => kind === "drop")).toMatchObject({ anchorFrame: anchor.observedFrame, observedFrame: next.observedFrame, inputSha256: next.observedFrame.frameHash }); expect(() => controller.replay(plan("run-a", anchor.observedFrame, { relation: "next" }))).toThrow("TASK19_FRAME_REPLAY_RELATION_INVALID"); });
  test("compacts long diagnostic histories while preserving head and tail evidence", () => { const controller = createTask19FrameController({ runId: "run-a" }); for (let sequence = 1; sequence <= 1_000; sequence += 1) observe(controller, `{"type":"invalidation","server_epoch":7,"sequence":${sequence},"resource":"queue","revision":${sequence}}`, metadata({ sequence })); const diagnostics = controller.diagnostics(); expect(diagnostics.length).toBeLessThanOrEqual(385); expect(diagnostics[0].observedFrame.sequence).toBe("1"); expect(diagnostics.find(({ kind }) => kind === "omitted")).toMatchObject({ count: 1_616 }); expect(diagnostics.at(-1).observedFrame.sequence).toBe("1000"); });
});
