import { describe, expect, test } from "bun:test";
import { createTask19WaiterRegistry } from "./task19-sidecar-proxy.mjs";

const fixture = () => { let monotonic = 100; const timers = []; const cleared = []; const registry = createTask19WaiterRegistry({ runId: "run-diagnostic", now: () => monotonic++, lifecycle: () => ({ closed: false, upstreamConnected: true, bearerToken: undefined }), setTimer: (callback, timeoutMs) => { const timer = { callback, timeoutMs }; timers.push(timer); return timer; }, clearTimer: (timer) => cleared.push(timer) }); return { registry, timers, cleared }; };
const selector = (sequence) => ({ kind: "snapshot", method: null, route: null, status: null, resource: null, epoch: null, sequence, revision: null, pageTargetId: "target-main" });

describe("Task19 sidecar waiter timeout diagnostics", () => {
  test("reports immutable selector, clock, lifecycle, bounded metadata-only tail and cleans the timed-out waiter", async () => { const value = fixture(); const waiting = value.registry.add({ ownerId: 17, stage: "initial-snapshot-await", selector: selector(99), matches: (kind, envelope) => kind === "envelope" && envelope.sequence === 99, timeoutMs: 20_000, timeoutCode: "TASK19_CAPTURE_ENVELOPE_TIMEOUT" }); const rejected = waiting.catch((error) => error); for (let sequence = 1; sequence <= 12; sequence += 1) value.registry.settle("envelope", { type: "invalidation", server_epoch: "7", sequence, revision: sequence, resource: "queue", zone_id: "main", token: "forbidden", body: { secret: "forbidden" }, observedFrame: { frameId: `frame-${sequence}`, frameHash: "a".repeat(64), payloadHash: "b".repeat(64) } }); value.timers[0].callback(); const error = await rejected; expect(error.code).toBe("TASK19_CAPTURE_ENVELOPE_TIMEOUT"); expect(error.detail).toMatchObject({ runId: "run-diagnostic", requestId: 17, stage: "initial-snapshot-await", createdAtMonotonicMs: 100, deadlineMonotonicMs: 20_100, selector: selector(99), observedEnvelopeCount: 12, lifecycle: { closed: false, upstreamConnected: true } }); expect(error.detail.observedEnvelopeTail).toHaveLength(10); expect(error.detail.observedEnvelopeTail.map(({ sequence }) => sequence)).toEqual([3, 4, 5, 6, 7, 8, 9, 10, 11, 12]); expect(JSON.stringify(error.detail)).not.toMatch(/forbidden|token|secret|body/i); expect(Object.isFrozen(error.detail)).toBe(true); expect(value.registry.pending()).toEqual([]); });

  test("includes other pending waiter selectors and removes only the waiter that timed out", async () => { const value = fixture(); const first = value.registry.add({ ownerId: 21, stage: "first", selector: selector(1), matches: () => false, timeoutMs: 1_000, timeoutCode: "TASK19_CAPTURE_ENVELOPE_TIMEOUT" }); const second = value.registry.add({ ownerId: 22, stage: "second", selector: selector(2), matches: () => false, timeoutMs: 2_000, timeoutCode: "TASK19_CAPTURE_ENVELOPE_TIMEOUT" }); const firstError = first.catch((error) => error); const secondError = second.catch((error) => error); value.timers[0].callback(); const error = await firstError; expect(error.detail.pendingWaiters).toEqual([{ requestId: 22, stage: "second", selector: selector(2), createdAtMonotonicMs: 101, deadlineMonotonicMs: 2_101 }]); expect(value.registry.pending()).toEqual(error.detail.pendingWaiters); value.registry.cancel(22); expect((await secondError).code).toBe("TASK19_CAPTURE_ABORTED"); expect(value.registry.pending()).toEqual([]); expect(value.cleared).toContain(value.timers[1]); });
});
