import { describe, expect, test } from "bun:test";
import { EventEmitter } from "node:events";
import { PassThrough } from "node:stream";
import { access, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { launchOwnedChromium } from "./task19-owned-chromium.mjs";

const executable = "/owned/chromium"; const digest = "a".repeat(64);
const fixture = ({ pid = 4242, spawnfile = executable } = {}) => { const child = new EventEmitter(); child.pid = pid; child.spawnfile = spawnfile; child.exitCode = null; child.signalCode = null; child.stderr = new PassThrough(); child.kill = () => {}; const context = { newPage: async () => page }; const page = { context: () => context }; let connected = true; let spawnArgs; const browser = { contexts: () => [context], isConnected: () => connected, close: async () => { connected = false; child.exitCode = 0; child.emit("exit", 0, null); } }; const chromium = { executablePath: () => executable, connectOverCDP: async () => browser }; const spawn = (_path, args) => { spawnArgs = args; queueMicrotask(() => child.stderr.write("DevTools listening on ws://127.0.0.1/devtools/browser/owned\n")); return child; }; return { child, context, page, browser, chromium, spawn, get spawnArgs() { return spawnArgs; } }; };
const launch = async (value, root, runId = "run-a") => launchOwnedChromium({ chromium: value.chromium, runId, root, spkiPins: "pin", spawn: value.spawn, hashExecutable: async () => digest, treeExited: () => true, terminate: (child) => { child.signalCode = "SIGKILL"; child.emit("exit", null, "SIGKILL"); } });

 describe("Task19 owned Chromium receipt identity", () => {
  test("binds the direct child, executable, profile, run, context and exact page target immutably", async () => { const root = await mkdtemp(join(tmpdir(), "task19-owned-test-")); try { const value = fixture(); const owner = await launch(value, root); const evidence = owner.capture({ expectedRunId: "run-a", targetId: "target-a", observedPage: value.page }); expect(evidence).toMatchObject({ pid: 4242, executablePath: executable, executableSha256: digest, spawnfile: executable, runId: "run-a", targetId: "target-a", aliveAtCapture: true, wrapper: false }); expect(Object.isFrozen(evidence)).toBe(true); expect(() => { evidence.pid = 9; }).toThrow(); const profile = join(root, evidence.profileId); await access(profile); const exited = await owner.close(); expect(exited).toEqual({ pid: 4242, exited: true, treeExited: true, exitCode: 0, signalCode: null, profileRemoved: true }); await expect(access(profile)).rejects.toThrow(); } finally { await rm(root, { recursive: true, force: true }); } });

  test("rejects missing and wrapper process handles at the launch boundary", async () => { for (const input of [{ pid: 0 }, { spawnfile: "/wrapper/sh" }]) { const root = await mkdtemp(join(tmpdir(), "task19-owned-test-")); try { const value = fixture(input); await expect(launch(value, root)).rejects.toThrow("TASK19_CHROMIUM_CHILD_IDENTITY_INVALID"); } finally { await rm(root, { recursive: true, force: true }); } } });

  test("launches a single owned Chromium process without a zygote tree", async () => { const root = await mkdtemp(join(tmpdir(), "task19-owned-test-")); try { const value = fixture(); const owner = await launch(value, root); expect(value.spawnArgs).toContain("--single-process"); expect(value.spawnArgs).toContain("--no-zygote"); await owner.close(); } finally { await rm(root, { recursive: true, force: true }); } });

  test("rejects wrong-run, page-target drift, stale PID reuse and evidence after exit", async () => { const root = await mkdtemp(join(tmpdir(), "task19-owned-test-")); try { const value = fixture(); const owner = await launch(value, root); expect(() => owner.capture({ expectedRunId: "run-b", targetId: "target-a", observedPage: value.page })).toThrow("TASK19_CHROMIUM_WRONG_RUN"); expect(() => owner.capture({ expectedRunId: "run-a", targetId: "target-a", observedPage: { context: () => value.context } })).toThrow("TASK19_CHROMIUM_PAGE_TARGET_MISMATCH"); owner.capture({ expectedRunId: "run-a", targetId: "target-a", observedPage: value.page }); expect(() => owner.capture({ expectedRunId: "run-a", targetId: "target-b", observedPage: value.page })).toThrow("TASK19_CHROMIUM_PAGE_TARGET_MISMATCH"); value.child.pid = 5252; expect(() => owner.capture({ expectedRunId: "run-a", targetId: "target-a", observedPage: value.page })).toThrow("TASK19_CHROMIUM_PID_STALE_OR_REUSED"); value.child.pid = 4242; await owner.close(); expect(() => owner.capture({ expectedRunId: "run-a", targetId: "target-a", observedPage: value.page })).toThrow("TASK19_CHROMIUM_EVIDENCE_AFTER_EXIT"); } finally { await rm(root, { recursive: true, force: true }); } });
});
