import { describe, expect, test } from "bun:test";
import { provisionQueueBatches, Task19ScaleBatchError } from "./task19-scenario-provisioner.mjs";

const wireFixture = ({ mutate = () => {}, onPost } = {}) => {
  const zones = new Map(["zone-a", "zone-b"].map((id) => [id, { revision: 0, queue: [] }])); const captures = []; const events = []; const calls = []; let sequence = 0;
  const take = (items, predicate) => { const index = items.findIndex(predicate); if (index < 0) throw new Error("TEST_SUBSCRIPTION_NOT_ARMED"); return items.splice(index, 1)[0]; };
  const capture = { next: ({ method, route, signal }) => new Promise((resolve, reject) => { const item = { method, route, resolve, reject }; captures.push(item); signal?.addEventListener("abort", () => { const index = captures.indexOf(item); if (index >= 0) captures.splice(index, 1); reject(new Error("ABORTED")); }, { once: true }); }), nextEvent: (resource, _timeout, { zoneId, signal } = {}) => new Promise((resolve, reject) => { const item = { resource, zoneId, resolve, reject }; events.push(item); signal?.addEventListener("abort", () => { const index = events.indexOf(item); if (index >= 0) events.splice(index, 1); reject(new Error("ABORTED")); }, { once: true }); }) };
  const request = async (input) => {
    calls.push(structuredClone({ method: input.method, path: input.path, headers: input.headers, body: input.body })); const match = /^\/api\/v1\/zones\/([^/]+)\/queue$/.exec(input.path); const zoneId = decodeURIComponent(match?.[1] ?? ""); const zone = zones.get(zoneId); if (!zone) return { status: 404, headers: {}, body: { code: "NOT_FOUND" } };
    if (input.method === "GET") return { status: 200, headers: {}, body: { zone_id: zoneId, revision: zone.revision, queue: structuredClone(zone.queue) } };
    await onPost?.({ input, zoneId, zone, calls }); const prior = zone.revision; const ids = input.body.track_ids.map((_track, index) => `${zoneId}:entry:${String(zone.queue.length + index + 1).padStart(4, "0")}`); zone.revision += 1; zone.queue.push(...ids.map((entry_id, index) => ({ entry_id, track_id: input.body.track_ids[index], position: zone.queue.length + index + 1 }))); const response = { status: 201, headers: { etag: `"${zone.revision}"` }, body: { revision: zone.revision, entry_ids: [...ids] } }; const observed = { request: { method: input.method, route: input.path, headers: { ifMatch: input.headers["if-match"], idempotencyKey: input.headers["idempotency-key"], correlationId: input.headers["x-request-id"], authorization: "bearer" }, body: structuredClone(input.body) }, response: structuredClone(response) }; const event = { type: "invalidation", resource: "queue", zone_id: zoneId, revision: zone.revision, sequence: ++sequence }; mutate({ input, zoneId, prior, observed, event, response, ids, zone }); take(captures, (item) => item.method === input.method && item.route === input.path).resolve(observed); take(events, (item) => item.resource === "queue" && item.zoneId === zoneId).resolve(event); return response;
  };
  return { credentials: { token: "controller", capture }, request, calls, zones, pending: () => ({ captures: captures.length, events: events.length }) };
};

const input = (fixture) => ({ runId: "run-batches", credentials: fixture.credentials, request: fixture.request, zones: [{ zoneId: "zone-a", revision: 0 }, { zoneId: "zone-b", revision: 0 }], trackIds: Array.from({ length: 6 }, (_, index) => `track-${index + 1}`), entriesPerZone: 6, batchSize: 2, concurrency: 2, timeoutMs: 1_000 });

describe("Task19 production queue batch correlation", () => {
  test("captures immutable ordered per-zone wire/event material with bounded cross-zone concurrency", async () => {
    const fixture = wireFixture(); const material = await provisionQueueBatches(input(fixture)); expect(Object.isFrozen(material)).toBe(true); expect(material).toMatchObject({ entryCount: 12, batchCount: 6, concurrency: 2 }); expect(material.zones).toHaveLength(2); expect(material.zones.every((zone) => zone.entryCount === 6 && zone.batches.length === 3 && zone.finalRevision === 3 && zone.finalEtag === '"3"')).toBe(true); expect(new Set(material.zones.flatMap((zone) => zone.entryIds)).size).toBe(12); expect(material.zones[0].representatives).toEqual({ first: { entryId: "zone-a:entry:0001", trackId: "track-1" }, middle: { entryId: "zone-a:entry:0004", trackId: "track-4" }, last: { entryId: "zone-a:entry:0006", trackId: "track-6" } }); expect(material.zones.flatMap((zone) => zone.batches).every((batch) => batch.event.revision === batch.response.revision && batch.request.headers.ifMatch === `"${batch.response.revision - 1}"`)).toBe(true); expect(fixture.calls.filter((call) => call.method === "POST")).toHaveLength(6); expect(fixture.pending()).toEqual({ captures: 0, events: 0 });
  });

  test.each([
    ["duplicate entry ID", ({ observed, response }) => { observed.response.body.entry_ids[1] = observed.response.body.entry_ids[0]; response.body.entry_ids[1] = response.body.entry_ids[0]; }, "TASK19_SCALE_ENTRY_ID_INVALID"],
    ["partial response", ({ observed, response }) => { observed.response.body.entry_ids.pop(); response.body.entry_ids.pop(); }, "TASK19_SCALE_BATCH_RESPONSE_PARTIAL"],
    ["equal revision", ({ observed, event, response, prior }) => { observed.response.body.revision = prior; observed.response.headers.etag = `"${prior}"`; response.body.revision = prior; response.headers.etag = `"${prior}"`; event.revision = prior; }, "TASK19_SCALE_BATCH_REVISION_INVALID"],
    ["stale revision", ({ observed, event, response, prior }) => { observed.response.body.revision = prior - 1; observed.response.headers.etag = `"${prior - 1}"`; response.body.revision = prior - 1; response.headers.etag = `"${prior - 1}"`; event.revision = prior - 1; }, "TASK19_SCALE_BATCH_REVISION_INVALID"],
    ["skipped revision", ({ observed, event, response }) => { observed.response.body.revision += 1; observed.response.headers.etag = `"${observed.response.body.revision}"`; response.body.revision = observed.response.body.revision; response.headers.etag = observed.response.headers.etag; event.revision = observed.response.body.revision; }, "TASK19_SCALE_BATCH_REVISION_INVALID"],
    ["wrong zone event", ({ event }) => { event.zone_id = "zone-other"; }, "TASK19_SCALE_BATCH_EVENT_INVALID"],
    ["header mismatch", ({ observed }) => { observed.request.headers.ifMatch = '"99"'; }, "TASK19_SCALE_BATCH_WIRE_INVALID"],
    ["replayed key response", ({ observed, response }) => { observed.response.status = 200; response.status = 200; }, "TASK19_SCALE_BATCH_WIRE_INVALID"],
    ["out-of-order response IDs", ({ observed, response }) => { observed.response.body.entry_ids.reverse(); response.body.entry_ids.reverse(); }, "TASK19_SCALE_QUEUE_FINAL_INVALID"],
  ])("rejects %s", async (_name, mutation, code) => { let mutated = false; const fixture = wireFixture({ mutate: (value) => { if (!mutated && value.zoneId === "zone-a") { mutated = true; mutation(value); } } }); try { await provisionQueueBatches(input(fixture)); throw new Error("TEST_EXPECTED_FAILURE"); } catch (error) { expect(error).toBeInstanceOf(Task19ScaleBatchError); expect(error.cause.message).toBe(code); expect(Object.isFrozen(error.material)).toBe(true); } expect(fixture.pending()).toEqual({ captures: 0, events: 0 }); });

  test("cancels independent zone work while retaining completed ownership material", async () => {
    let releaseFailure; const failure = new Promise((resolve) => { releaseFailure = resolve; }); const fixture = wireFixture({ onPost: async ({ zoneId, zone }) => { if (zoneId === "zone-a" && zone.revision === 1) releaseFailure(); if (zoneId === "zone-b") { await failure; throw new Error("INJECTED_PARTIAL_BATCH_FAILURE"); } } }); try { await provisionQueueBatches(input(fixture)); throw new Error("TEST_EXPECTED_FAILURE"); } catch (error) { expect(error).toBeInstanceOf(Task19ScaleBatchError); expect(error.cause.message).toBe("INJECTED_PARTIAL_BATCH_FAILURE"); expect(error.material.entryCount).toBeGreaterThan(0); expect(error.material.entryCount).toBeLessThan(12); } expect(fixture.pending()).toEqual({ captures: 0, events: 0 });
  });
});
