import { describe, expect, test } from "bun:test";
import { createBoundedMetadataTail, createRawWebSocketFrameObserver, sanitizeWebSocketRequest, sanitizeWebSocketResponse } from "./task19-websocket-diagnostic.mjs";

const maskedFrame = (payload) => { const bytes = Buffer.from(payload); const mask = Buffer.from([1, 2, 3, 4]); const encoded = Buffer.from(bytes.map((value, index) => value ^ mask[index % 4])); return Buffer.concat([Buffer.from([0xc1, 0x80 | bytes.length]), mask, encoded]); };

describe("Task19 WebSocket transport diagnostics", () => {
  test("captures complete sanitized handshake semantics without ticket or authorization values", () => { const request = sanitizeWebSocketRequest({ url: "/api/v1/events?ticket=forbidden", headers: { upgrade: "WebSocket", connection: "keep-alive, Upgrade", "sec-websocket-version": "13", "sec-websocket-protocol": "jastreamer.bearer.forbidden", "sec-websocket-extensions": "permessage-deflate; client_max_window_bits", origin: "https://control.example", authorization: "Bearer forbidden", cookie: "secret=forbidden" } }); const response = sanitizeWebSocketResponse({ status: 101, headers: { upgrade: "websocket", connection: "Upgrade", "sec-websocket-extensions": "permessage-deflate" } }); expect(request).toEqual({ path: "/api/v1/events", queryPresent: true, upgrade: "websocket", connection: ["keep-alive", "upgrade"], version: "13", protocol: "present-redacted", extensions: "permessage-deflate; client_max_window_bits", origin: "https://control.example", authorizationPresent: true, cookiePresent: true }); expect(response.extensions).toBe("permessage-deflate"); expect(JSON.stringify({ request, response })).not.toContain("forbidden"); expect(Object.isFrozen(request)).toBe(true); });

  test("observes fragmented delivery as one exact masked frame without exposing payload", () => { const observations = []; const observe = createRawWebSocketFrameObserver({ direction: "client-to-server", connectionId: "ws-7", observe: (value) => observations.push(value) }); const bytes = maskedFrame("private"); observe(bytes.subarray(0, 3)); expect(observations).toEqual([]); observe(bytes.subarray(3)); expect(observations).toHaveLength(1); expect(observations[0]).toMatchObject({ connectionId: "ws-7", direction: "client-to-server", fin: true, rsv1: true, rsv2: false, rsv3: false, opcode: 1, masked: true, payloadLength: 7, decoderDisposition: "frame-complete", errorCode: null }); expect(observations[0].frameSha256).toMatch(/^[0-9a-f]{64}$/); expect(observations[0].payloadSha256).toMatch(/^[0-9a-f]{64}$/); expect(JSON.stringify(observations)).not.toContain("private"); });

  test("bounds metadata tails and records a typed invalid-length disposition", () => { const tail = createBoundedMetadataTail(10); for (let index = 0; index < 12; index += 1) tail.observe({ index }); expect(tail.snapshot().map(({ index }) => index)).toEqual([2, 3, 4, 5, 6, 7, 8, 9, 10, 11]); const errors = []; const observe = createRawWebSocketFrameObserver({ direction: "server-to-client", connectionId: "ws-bad", maxPayloadBytes: 4, observe: (value) => errors.push(value) }); observe(Buffer.from([0x81, 0x05])); expect(errors[0]).toMatchObject({ decoderDisposition: "frame-length-invalid", errorCode: "TASK19_SIDECAR_FRAME_INVALID", payloadLength: 5 }); });
});
