name: jastreamer_control
description: jastreamer Control client.
publish_to: none
version: 0.1.0
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  crypto: 3.0.6
  http: 1.5.0
  web_socket_channel: 3.0.3
  url_launcher: 6.3.2
  web: 1.1.1
dev_dependencies:
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  msix: 3.18.0
msix_config:
  display_name: jastreamer Control
  publisher_display_name: jastreamer
  identity_name: io.jastreamer.control
  msix_version: 0.1.0.0
  capabilities: internetClient
flutter:
  uses-material-design: true
