import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { expectedProviderArtifactName, observeProviderArtifacts, serializeProviderObservations, type ProviderApiArtifact, type ProviderRunContext } from "./qualification-provider-observer";

type JsonRecord = Record<string, unknown>;
const fail = (code: string): never => { throw new Error(code); };
const record = (value: unknown): JsonRecord => typeof value === "object" && value !== null && !Array.isArray(value) ? Object.fromEntries(Object.entries(value)) : fail("PROVIDER_OBSERVER_INPUT_INVALID");
const text = (value: unknown): string => typeof value === "string" ? value : fail("PROVIDER_OBSERVER_INPUT_INVALID");
const integer = (value: unknown): number => typeof value === "number" && Number.isSafeInteger(value) && value > 0 ? value : fail("PROVIDER_OBSERVER_INPUT_INVALID");
const arguments_ = process.argv.slice(2); if (arguments_.length !== 6 || arguments_[0] !== "--context" || arguments_[2] !== "--output-root" || arguments_[4] !== "--output") fail("PROVIDER_OBSERVER_USAGE");
const token = process.env["GITHUB_TOKEN"]; const api = process.env["GITHUB_API_URL"] ?? "https://api.github.com"; if (token === undefined || token.length < 1 || !/^https:\/\/[A-Za-z0-9.-]+$/.test(api)) fail("PROVIDER_OBSERVER_ENV_INVALID");
const rawContext = record(JSON.parse(readFileSync(arguments_[1] ?? fail("PROVIDER_OBSERVER_USAGE"), "utf8"))); const requested: Omit<ProviderRunContext, "observedAt"> = { repository: rawContext["repository"] === "furyheimdall/jastreamer" ? rawContext["repository"] : fail("PROVIDER_OBSERVER_INPUT_INVALID"), runId: text(rawContext["runId"]), runAttempt: integer(rawContext["runAttempt"]), headSha: text(rawContext["headSha"]) }; const outputRoot = resolve(arguments_[3] ?? fail("PROVIDER_OBSERVER_USAGE"));
const headers = { authorization: `Bearer ${token}`, accept: "application/vnd.github+json", "x-github-api-version": "2022-11-28", "cache-control": "no-cache, no-store", pragma: "no-cache", "user-agent": "jastreamer-qualification-observer" };
let providerDate: string | undefined; const get = async (path: string, binary = false): Promise<unknown> => { const response = await fetch(`${api}${path}`, { method: "GET", headers, redirect: "follow", cache: "no-store" }); if (!response.ok) fail("PROVIDER_OBSERVER_READ_FAILED"); const responseDate = response.headers.get("date"); if (responseDate === null || !Number.isFinite(Date.parse(responseDate))) throw new Error("PROVIDER_OBSERVER_DATE_INVALID"); providerDate = responseDate; return binary ? new Uint8Array(await response.arrayBuffer()) : response.json(); };
const repositoryPath = requested.repository.split("/").map(encodeURIComponent).join("/"); const run = record(await get(`/repos/${repositoryPath}/actions/runs/${requested.runId}`)); const repository = record(run["repository"]); if (String(run["id"]) !== requested.runId || run["run_attempt"] !== requested.runAttempt || run["head_sha"] !== requested.headSha || repository["full_name"] !== requested.repository) fail("PROVIDER_RUN_INVALID"); const context: ProviderRunContext = { ...requested, observedAt: providerDate ?? fail("PROVIDER_OBSERVER_DATE_INVALID") };
const pages: ProviderApiArtifact[][] = []; let total: number | undefined; for (let page = 1; page <= 100; page += 1) { const response = record(await get(`/repos/${repositoryPath}/actions/runs/${context.runId}/artifacts?per_page=100&page=${page}`)); if (!Array.isArray(response["artifacts"]) || typeof response["total_count"] !== "number") fail("PROVIDER_PAGINATION_INVALID"); const responseTotal = response["total_count"] as number; if (total === undefined) total = responseTotal; else if (total !== responseTotal) fail("PROVIDER_PAGINATION_CHANGED"); const values = response["artifacts"] as ProviderApiArtifact[]; pages.push(values.map((artifact) => ({ ...artifact, workflow_run: { id: context.runId, run_attempt: context.runAttempt, head_sha: context.headSha, repository: context.repository } }))); if (values.length < 100) break; }
if (total === undefined || pages.flat().length !== total) fail("PROVIDER_PAGINATION_INCOMPLETE"); const expectedNames = new Set(["server", "control"].flatMap((component) => ["publication-stage", "staging-binding"].map((kind) => expectedProviderArtifactName(component as "server" | "control", kind as "publication-stage" | "staging-binding", context.runId, context.runAttempt)))); const archives: Record<string, Uint8Array> = {}; for (const artifact of pages.flat()) { const artifactId = String(artifact.id); if (typeof artifact.name === "string" && expectedNames.has(artifact.name) && /^[1-9][0-9]*$/.test(artifactId)) archives[artifactId] = await get(`/repos/${repositoryPath}/actions/artifacts/${artifactId}/zip`, true) as Uint8Array; }
const observed = observeProviderArtifacts(context, pages, archives); const serialized = serializeProviderObservations(observed, (relativePath, bytes) => { const destination = join(outputRoot, relativePath); mkdirSync(dirname(destination), { recursive: true }); writeFileSync(destination, bytes); return destination; });
writeFileSync(arguments_[5] ?? fail("PROVIDER_OBSERVER_USAGE"), `${JSON.stringify(serialized, null, 2)}\n`); console.log(JSON.stringify({ status: "observed", artifacts: serialized.map(({ id, name, digest, size, createdAt, expiresAt }) => ({ id, name, digest, size, createdAt, expiresAt })) }));
