import { createHash } from "node:crypto";
import { deflateRawSync } from "node:zlib";
import { describe, expect, test } from "bun:test";
import { authenticateTask19ProviderArtifact, DEFAULT_ZIP_LIMITS, expectedProviderArtifactName, expectedTask19ArtifactName, inspectProviderZip, observeProviderArtifacts, observeTask19ProviderArtifact, type ProviderApiArtifact, type ProviderRunContext, type Task19ProviderContext } from "./qualification-provider-observer";

const sha = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex");
const crcTable = Array.from({ length: 256 }, (_, index) => { let value = index; for (let bit = 0; bit < 8; bit += 1) value = (value & 1) === 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1; return value >>> 0; });
const crc = (bytes: Uint8Array): number => { let value = 0xffffffff; for (const byte of bytes) value = (crcTable[(value ^ byte) & 255] ?? 0) ^ (value >>> 8); return (value ^ 0xffffffff) >>> 0; };
type ZipEntry = Readonly<{ name: string; bytes: Uint8Array; method?: 0 | 8; external?: number }>;
const zip = (entries: readonly ZipEntry[]): Uint8Array => { const locals: Buffer[] = []; const centrals: Buffer[] = []; let offset = 0; for (const entry of entries) { const name = Buffer.from(entry.name); const method = entry.method ?? 0; const body = method === 8 ? deflateRawSync(entry.bytes) : Buffer.from(entry.bytes); const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50); local.writeUInt16LE(20, 4); local.writeUInt16LE(method, 8); local.writeUInt32LE(crc(entry.bytes), 14); local.writeUInt32LE(body.length, 18); local.writeUInt32LE(entry.bytes.length, 22); local.writeUInt16LE(name.length, 26); locals.push(local, name, body); const central = Buffer.alloc(46); central.writeUInt32LE(0x02014b50); central.writeUInt16LE(0x0314, 4); central.writeUInt16LE(20, 6); central.writeUInt16LE(method, 10); central.writeUInt32LE(crc(entry.bytes), 16); central.writeUInt32LE(body.length, 20); central.writeUInt32LE(entry.bytes.length, 24); central.writeUInt16LE(name.length, 28); central.writeUInt32LE((entry.external ?? (0o100644 << 16)) >>> 0, 38); central.writeUInt32LE(offset, 42); centrals.push(central, name); offset += local.length + name.length + body.length; } const centralBytes = Buffer.concat(centrals); const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50); end.writeUInt16LE(entries.length, 8); end.writeUInt16LE(entries.length, 10); end.writeUInt32LE(centralBytes.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...locals, centralBytes, end]); };
const descriptorZip = (nameValue: string, bytes: Uint8Array, declaredSize = bytes.length): Uint8Array => { const name = Buffer.from(nameValue); const body = deflateRawSync(bytes); const checksum = crc(bytes); const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50); local.writeUInt16LE(20, 4); local.writeUInt16LE(8, 6); local.writeUInt16LE(8, 8); local.writeUInt16LE(name.length, 26); const descriptor = Buffer.alloc(16); descriptor.writeUInt32LE(0x08074b50); descriptor.writeUInt32LE(checksum, 4); descriptor.writeUInt32LE(body.length, 8); descriptor.writeUInt32LE(declaredSize, 12); const central = Buffer.alloc(46); central.writeUInt32LE(0x02014b50); central.writeUInt16LE(0x0314, 4); central.writeUInt16LE(20, 6); central.writeUInt16LE(8, 8); central.writeUInt16LE(8, 10); central.writeUInt32LE(checksum, 16); central.writeUInt32LE(body.length, 20); central.writeUInt32LE(declaredSize, 24); central.writeUInt16LE(name.length, 28); central.writeUInt32LE((0o100644 << 16) >>> 0, 38); const centralOffset = local.length + name.length + body.length + descriptor.length; const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50); end.writeUInt16LE(1, 8); end.writeUInt16LE(1, 10); end.writeUInt32LE(central.length + name.length, 12); end.writeUInt32LE(centralOffset, 16); return Buffer.concat([local, name, body, descriptor, central, name, end]); };
const centralOffset = (archive: Uint8Array): number => Buffer.from(archive).readUInt32LE(archive.length - 6);
const context: ProviderRunContext = { repository: "furyheimdall/jastreamer", runId: "1001", runAttempt: 2, headSha: "a".repeat(40), observedAt: "2026-08-26T12:00:00Z" };
const fixture = () => { const archives: Record<string, Uint8Array> = {}; const records: ProviderApiArtifact[] = []; let next = 2000; for (const component of ["server", "control"] as const) for (const kind of ["publication-stage", "staging-binding"] as const) { next += 1; const id = String(next); const entries = kind === "publication-stage" ? [{ name: "qualification/candidate-binding.json", bytes: Buffer.from(`{"component":"${component}"}\n`) }, { name: "qualification/content-manifest.json", bytes: Buffer.from("{}\n") }, { name: `publication-stage/${component}.bin`, bytes: Buffer.from(component) }] : [{ name: `${component}-publication-staging.json`, bytes: Buffer.from(`{"component":"${component}"}\n`) }]; const archive = zip(entries); archives[id] = archive; records.push({ id, name: expectedProviderArtifactName(component, kind, context.runId, context.runAttempt), digest: `sha256:${sha(archive)}`, size_in_bytes: archive.length, created_at: "2026-08-26T11:00:00Z", expires_at: "2026-08-27T12:00:00Z", expired: false, workflow_run: { id: "1001", run_attempt: 2, head_sha: "a".repeat(40), repository: "furyheimdall/jastreamer" } }); } return { records, archives }; };
const required = <T>(value: T | undefined): T => { if (value === undefined) throw new Error("TEST_FIXTURE_INVALID"); return value; };
const changed = (index: number, patch: Partial<ProviderApiArtifact>) => { const value = fixture(); const current = value.records[index]; if (current === undefined) throw new Error("TEST_FIXTURE_INVALID"); value.records[index] = { ...current, ...patch }; return value; };

describe("read-only complete provider artifact observation", () => {
  test("accepts runtime-shaped provider records and actual ZIP archives", () => { const value = fixture(); const observed = observeProviderArtifacts(context, [value.records], value.archives); expect(observed).toHaveLength(4); expect(observed[0]?.entries["qualification/candidate-binding.json"]).toBeDefined(); });
  test("rejects missing duplicate expired and namespace collisions", () => { const missing = fixture(); missing.records.shift(); expect(() => observeProviderArtifacts(context, [missing.records], missing.archives)).toThrow("PROVIDER_ARTIFACT_MISSING"); const duplicate = fixture(); duplicate.records.push({ ...required(duplicate.records[0]), id: 9999 }); expect(() => observeProviderArtifacts(context, [duplicate.records], duplicate.archives)).toThrow("PROVIDER_ARTIFACT_DUPLICATE"); const expired = changed(0, { expired: true }); expect(() => observeProviderArtifacts(context, [expired.records], expired.archives)).toThrow("PROVIDER_ARTIFACT_EXPIRED"); const collision = fixture(); collision.records.push({ ...required(collision.records[0]), id: 9998, name: "server-publication-stage-999-99" }); expect(() => observeProviderArtifacts(context, [collision.records], collision.archives)).toThrow("PROVIDER_ARTIFACT_COLLISION"); });
  test.each([["run", { workflow_run: { id: "999", run_attempt: 2, head_sha: "a".repeat(40), repository: "furyheimdall/jastreamer" } }], ["attempt", { workflow_run: { id: "1001", run_attempt: 99, head_sha: "a".repeat(40), repository: "furyheimdall/jastreamer" } }], ["repository", { workflow_run: { id: "1001", run_attempt: 2, head_sha: "a".repeat(40), repository: "evil/repo" } }], ["SHA", { workflow_run: { id: "1001", run_attempt: 2, head_sha: "b".repeat(40), repository: "furyheimdall/jastreamer" } }]])("rejects wrong provider %s", (_name, patch) => { const value = changed(0, patch); expect(() => observeProviderArtifacts(context, [value.records], value.archives)).toThrow("PROVIDER_ARTIFACT_INVALID"); });
  test("rejects stale provider timestamps", () => { const future = changed(0, { created_at: "2026-08-27T12:00:00Z" }); expect(() => observeProviderArtifacts(context, [future.records], future.archives)).toThrow("PROVIDER_ARTIFACT_STALE"); const expired = changed(0, { expires_at: "2026-08-26T11:59:59Z" }); expect(() => observeProviderArtifacts(context, [expired.records], expired.archives)).toThrow("PROVIDER_ARTIFACT_STALE"); });
  test("rejects wrong name digest and size", () => { const name = changed(0, { name: "server-publication-stage-999-99" }); expect(() => observeProviderArtifacts(context, [name.records], name.archives)).toThrow(); const digest = changed(0, { digest: `sha256:${"f".repeat(64)}` }); expect(() => observeProviderArtifacts(context, [digest.records], digest.archives)).toThrow("PROVIDER_ARCHIVE_DIGEST_MISMATCH"); const size = changed(0, { size_in_bytes: 999 }); expect(() => observeProviderArtifacts(context, [size.records], size.archives)).toThrow("PROVIDER_ARCHIVE_DIGEST_MISMATCH"); });
  test("rejects archive digest mismatch and unsafe ZIP inventories", () => { const base = fixture(); base.archives["2001"] = Uint8Array.from([...required(base.archives["2001"]), 0]); expect(() => observeProviderArtifacts(context, [base.records], base.archives)).toThrow("PROVIDER_ARCHIVE_DIGEST_MISMATCH"); for (const entries of [[{ name: "../escape", bytes: Buffer.from("x") }], [{ name: "link", bytes: Buffer.from("target"), external: 0o120777 << 16 }], [{ name: "same", bytes: Buffer.from("a") }, { name: "same", bytes: Buffer.from("b") }]]) expect(() => inspectProviderZip(zip(entries))).toThrow("ARTIFACT_ARCHIVE_ENTRY_INVALID"); });
  test("rejects extra missing and zip-bomb binding archives", () => { const extra = zip([{ name: "server-publication-staging.json", bytes: Buffer.from("{}") }, { name: "extra", bytes: Buffer.from("x") }]); const missing = zip([{ name: "other", bytes: Buffer.from("x") }]); const bomb = zip([{ name: "server-publication-staging.json", bytes: Buffer.alloc(2 * 1024 * 1024), method: 8 }]); for (const [archive, code] of [[extra, "PROVIDER_ARCHIVE_EXTRA_FILE"], [missing, "PROVIDER_ARCHIVE_REQUIRED_FILE_MISSING"], [bomb, "ARTIFACT_ARCHIVE_INVALID"]] as const) { const value = fixture(); value.archives["2002"] = archive; value.records[1] = { ...required(value.records[1]), size_in_bytes: archive.length, digest: `sha256:${sha(archive)}` }; expect(() => observeProviderArtifacts(context, [value.records], value.archives)).toThrow(code); } });
  test("bounds forged 32MiB descriptor expansion before declared-size comparison", () => { const archive = descriptorZip("bomb.bin", Buffer.alloc(32 * 1024 * 1024), 1); const bounds: number[] = []; const limits = { ...DEFAULT_ZIP_LIMITS, maxEntryBytes: 64 * 1024, maxTotalBytes: 64 * 1024, ratioSlackBytes: 0 }; expect(() => inspectProviderZip(archive, limits, { onInflateBound: (bound) => bounds.push(bound) })).toThrow("ARTIFACT_ARCHIVE_INVALID"); expect(bounds).toEqual([64 * 1024]); });
  test("accepts honest data descriptor and exact configured maximum", () => { const bytes = Buffer.alloc(64 * 1024, 7); const limits = { ...DEFAULT_ZIP_LIMITS, maxEntryBytes: bytes.length, maxTotalBytes: bytes.length, ratioSlackBytes: bytes.length }; expect(inspectProviderZip(descriptorZip("max.bin", bytes), limits)["max.bin"]?.length).toBe(bytes.length); });
  test("rejects local-central header flag method name CRC and size mismatches", () => { const original = zip([{ name: "entry.bin", bytes: Buffer.from("content") }]); const central = centralOffset(original); const mutations: Array<(bytes: Buffer) => void> = [(bytes) => bytes.writeUInt16LE(8, central + 10), (bytes) => bytes.writeUInt16LE(8, central + 8), (bytes) => { bytes[30] = 0x78; }, (bytes) => bytes.writeUInt32LE(0, 14), (bytes) => bytes.writeUInt32LE(1, 18), (bytes) => bytes.writeUInt32LE(1, 22), (bytes) => bytes.writeUInt32LE(0, central + 16)]; for (const mutate of mutations) { const forged = Buffer.from(original); mutate(forged); expect(() => inspectProviderZip(forged)).toThrow("ARTIFACT_ARCHIVE_INVALID"); } });
  test("rejects descriptor tricks encryption ZIP64 overlap truncation and trailing records", () => { const descriptor = Buffer.from(descriptorZip("entry.bin", Buffer.from("content"))); descriptor.writeUInt32LE(0, centralOffset(descriptor) - 12); expect(() => inspectProviderZip(descriptor)).toThrow("ARTIFACT_ARCHIVE_INVALID"); const unsupported = Buffer.from(zip([{ name: "entry.bin", bytes: Buffer.from("x") }])); unsupported.writeUInt16LE(99, 8); unsupported.writeUInt16LE(99, centralOffset(unsupported) + 10); expect(() => inspectProviderZip(unsupported)).toThrow("ARTIFACT_ARCHIVE_INVALID"); const nonUtf8 = zip([{ name: "é.bin", bytes: Buffer.from("x") }]); expect(() => inspectProviderZip(nonUtf8)).toThrow("ARTIFACT_ARCHIVE_ENTRY_INVALID"); const encrypted = Buffer.from(zip([{ name: "entry.bin", bytes: Buffer.from("x") }])); encrypted.writeUInt16LE(1, 6); encrypted.writeUInt16LE(1, centralOffset(encrypted) + 8); expect(() => inspectProviderZip(encrypted)).toThrow("ARTIFACT_ARCHIVE_INVALID"); const zip64 = Buffer.from(zip([{ name: "entry.bin", bytes: Buffer.from("x") }])); zip64.writeUInt32LE(0xffffffff, centralOffset(zip64) + 20); expect(() => inspectProviderZip(zip64)).toThrow("ARTIFACT_ARCHIVE_INVALID"); const overlap = Buffer.from(zip([{ name: "one", bytes: Buffer.from("1") }, { name: "two", bytes: Buffer.from("2") }])); const secondCentral = centralOffset(overlap) + 46 + Buffer.byteLength("one"); overlap.writeUInt32LE(0, secondCentral + 42); expect(() => inspectProviderZip(overlap)).toThrow("ARTIFACT_ARCHIVE_INVALID"); const honest = zip([{ name: "entry.bin", bytes: Buffer.from("x") }]); expect(() => inspectProviderZip(honest.slice(0, -1))).toThrow("ARTIFACT_ARCHIVE_INVALID"); expect(() => inspectProviderZip(Uint8Array.from([...honest, 0]))).toThrow("ARTIFACT_ARCHIVE_INVALID"); });
  test("rejects incomplete pagination", () => { const value = fixture(); expect(() => observeProviderArtifacts(context, [[], value.records], value.archives)).toThrow("PROVIDER_PAGINATION_INCOMPLETE"); });
});

const task19Context: Task19ProviderContext = { repository: "furyheimdall/jastreamer", workflowPath: ".github/workflows/product-qualification-dispatch.yml", eventName: "workflow_dispatch", runId: "1001", runAttempt: 2, headSha: "a".repeat(40), observedAt: "2026-08-26T12:00:00Z" };
const task19Fixture = (): Readonly<{ archive: Uint8Array; record: ProviderApiArtifact }> => {
  const payload = Buffer.from("candidate");
  const closure = Buffer.from(`${JSON.stringify({ schemaVersion: 2, kind: "task19_candidate_closure", source: { revision: task19Context.headSha }, files: { server: { path: "files/server", sha256: sha(payload), size: payload.length } }, receipts: {}, stagedManifest: { path: "files/staged", sha256: sha(payload), size: payload.length } })}\n`);
  const archive = zip([{ name: "task19-candidate-closure.json", bytes: closure }, { name: "files/server", bytes: payload }, { name: "files/staged", bytes: payload }]);
  return { archive, record: { id: "3001", name: expectedTask19ArtifactName(task19Context.runId, task19Context.runAttempt), digest: `sha256:${sha(archive)}`, size_in_bytes: archive.length, created_at: "2026-08-26T11:00:00Z", expires_at: "2026-08-27T12:00:00Z", expired: false, workflow_run: { id: task19Context.runId, run_attempt: task19Context.runAttempt, head_sha: task19Context.headSha, repository: task19Context.repository, conclusion: "success" } } };
};

describe("Task19 protected artifact provider observation", () => {
  test("authenticates metadata before archive bytes are downloaded", () => {
    const value = task19Fixture();
    expect(authenticateTask19ProviderArtifact(task19Context, [value.record])).toMatchObject({ artifactId: "3001", artifactName: expectedTask19ArtifactName("1001", 2), headSha: task19Context.headSha });
  });

  test("accepts only the exact current protected provider run identity and preserves authenticated size", () => {
    const value = task19Fixture();
    expect(observeTask19ProviderArtifact(task19Context, [value.record], value.archive).provider).toMatchObject({ headSha: task19Context.headSha, size: value.archive.byteLength });
  });

  test("rejects a provider run that has not concluded successfully before candidate acceptance", () => {
    const value = task19Fixture();
    const workflowRun = { id: task19Context.runId, run_attempt: task19Context.runAttempt, head_sha: task19Context.headSha, repository: task19Context.repository, conclusion: "failure" };
    expect(() => authenticateTask19ProviderArtifact(task19Context, [{ ...value.record, workflow_run: workflowRun }])).toThrow("PROVIDER_RUN_UNSUCCESSFUL");
  });

  test("rejects artifact size mismatch independently of digest mismatch", () => {
    const value = task19Fixture();
    const record = { ...value.record, size_in_bytes: value.archive.byteLength + 1 };
    expect(() => observeTask19ProviderArtifact(task19Context, [record], value.archive)).toThrow("PROVIDER_ARCHIVE_SIZE_MISMATCH");
  });

  test.each([
    ["repository", { repository: "evil/repo" }],
    ["run", { id: "999" }],
    ["attempt", { run_attempt: 9 }],
    ["current head SHA", { head_sha: "b".repeat(40) }],
  ])("rejects wrong artifact workflow-run %s", (_name, patch) => {
    const value = task19Fixture();
    const workflowRun = { id: task19Context.runId, run_attempt: task19Context.runAttempt, head_sha: task19Context.headSha, repository: task19Context.repository, conclusion: "success", ...patch };
    expect(() => observeTask19ProviderArtifact(task19Context, [{ ...value.record, workflow_run: workflowRun }], value.archive)).toThrow("PROVIDER_ARTIFACT_INVALID");
  });
});
