import { describe, expect, test } from "bun:test";
import { existsSync, readFileSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
const root = resolve(new URL("../..", import.meta.url).pathname);
const serverPath = ".github/workflows/server-release.yml"; const controlPath = ".github/workflows/control-release.yml"; const orchestratorPath = ".github/workflows/product-qualification-dispatch.yml"; const paths = [serverPath, controlPath, orchestratorPath];
const runBlocks = (workflow: string): readonly string[] => [...workflow.matchAll(/^([ ]+)run: \|\n((?:(?:\1  ).*\n?)*)/gm)].map((match) => match[2] ?? "");
describe("reusable qualification workflow input isolation", () => {
  test.each(["line\nPWNED", "'\nprintf PWNED", "$(printf PWNED)", "x\nprintf 'owned=true' >> $GITHUB_OUTPUT"])("caller input never enters shell source: %s", (payload) => { const sentinel = join(root, ".qualification-injection-sentinel"); rmSync(sentinel, { force: true }); for (const path of paths) { const rendered = readFileSync(join(root, path), "utf8").replaceAll(/\$\{\{\s*inputs\.[^}]+}}/g, payload); for (const script of runBlocks(rendered)) expect(script).not.toContain(payload); } expect(existsSync(sentinel)).toBe(false); });
  test("orchestrator is protected read-only scheduler wiring", () => { const workflow = readFileSync(join(root, orchestratorPath), "utf8"); expect(workflow).toContain("environment: product-qualification-dispatch"); expect(workflow).toContain("permissions: { contents: read }"); expect(workflow).not.toMatch(/actions:\s*write|contents:\s*write|packages:\s*write/); expect(workflow).not.toMatch(/gh\s|curl\s|\/dispatches/); expect(workflow).toContain("actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"); expect(workflow).toContain("persist-credentials: false"); });
  test("called workflows retain pinned trusted actions and protected signing environments", () => { for (const path of paths.slice(0, 2)) { const workflow = readFileSync(join(root, path), "utf8"); expect(workflow).toContain("workflow_call:"); expect(workflow).toContain("persist-credentials: false"); expect(workflow).not.toMatch(/uses:\s*[^\s]+@(main|master|v[0-9]+)\b/); } expect(readFileSync(join(root, serverPath), "utf8")).toContain("environment: server-signing"); const control = readFileSync(join(root, controlPath), "utf8"); expect(control).toContain("environment: control-android-signing"); expect(control).toContain("environment: control-windows-signing"); });
});
