import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { authorizeQualificationInvocation, type InvocationAuthorizationInput } from "./qualification-invocation-authorization";
const root = resolve(new URL("../..", import.meta.url).pathname); const workflow = (component: "server" | "control") => readFileSync(`${root}/.github/workflows/${component}-release.yml`, "utf8");
const valid: InvocationAuthorizationInput = { component: "server", mode: "authoritative", repository: "furyheimdall/jastreamer", runId: "1001", runAttempt: "2", ref: "refs/heads/main", sha: "a".repeat(40), refProtected: true, defaultBranch: "main", workflowRef: "furyheimdall/jastreamer/.github/workflows/product-qualification-dispatch.yml@refs/heads/main", caller: { runId: "1001", runAttempt: "2", ref: "refs/heads/main", sha: "a".repeat(40), workflowPath: ".github/workflows/product-qualification-dispatch.yml" } };
const { caller: _caller, ...withoutCaller } = valid;
const jobs = (source: string): Readonly<Record<string, string>> => Object.fromEntries([...source.matchAll(/^  ([a-z0-9-]+):\n([\s\S]*?)(?=^  [a-z0-9-]+:|\s*$)/gm)].map((match) => [match[1] ?? "", match[2] ?? ""]));
const dependencies = (block: string): readonly string[] => { const inline = /^    needs: \[([^\]]+)]/m.exec(block)?.[1]; if (inline !== undefined) return inline.split(",").map((value) => value.trim()); const scalar = /^    needs: ([a-z0-9-]+)$/m.exec(block)?.[1]; return scalar === undefined ? [] : [scalar]; };
const reaches = (graph: Readonly<Record<string, string>>, job: string, target: string, seen = new Set<string>()): boolean => { if (job === target) return true; if (seen.has(job)) return false; seen.add(job); return dependencies(graph[job] ?? "").some((dependency) => reaches(graph, dependency, target, seen)); };
describe("checkout-free invocation authorization", () => {
  test("accepts only the exact protected authoritative parent", () => { expect(authorizeQualificationInvocation(valid)).toBe(true); for (const changed of [{ ...valid, runId: "999" }, { ...valid, runAttempt: "99" }, { ...valid, ref: "refs/heads/evil" }, { ...valid, sha: "b".repeat(40) }, { ...valid, refProtected: false }, { ...valid, defaultBranch: "trunk" }, { ...valid, workflowRef: "furyheimdall/jastreamer/.github/workflows/evil.yml@refs/heads/main" }, { ...valid, caller: { runId: "1001", runAttempt: "2", ref: "refs/heads/main", sha: "a".repeat(40), workflowPath: ".github/workflows/evil.yml" } }]) expect(authorizeQualificationInvocation(changed)).toBe(false); });
  test("direct branch cannot impersonate authoritative mode and standalone modes are explicit", () => { expect(authorizeQualificationInvocation(withoutCaller)).toBe(false); expect(authorizeQualificationInvocation({ ...withoutCaller, mode: "standalone-staging", workflowRef: "furyheimdall/jastreamer/.github/workflows/server-release.yml@refs/heads/main" })).toBe(true); expect(authorizeQualificationInvocation({ ...withoutCaller, mode: "tag", refProtected: false, ref: "refs/tags/server-v1.2.3", workflowRef: "furyheimdall/jastreamer/.github/workflows/server-release.yml@refs/tags/server-v1.2.3" })).toBe(true); });
  test.each(["server", "control"] as const)("%s has no repository code before authorization and a closed DAG", (component) => { const source = workflow(component); const authorization = source.slice(source.indexOf("  invocation-authorization:"), source.indexOf("\n  validate:")); expect(authorization).not.toMatch(/uses:|checkout|secrets\.|contents:\s*write|actions:\s*write|packages:\s*write/); expect(authorization).toContain("permissions: {}"); expect(source).toMatch(/  validate:\n    needs: invocation-authorization\n    if: needs\.invocation-authorization\.result == 'success'/); const graph = jobs(source); for (const [job, block] of Object.entries(graph)) if (job !== "invocation-authorization" && /uses:|run:|actions:\s*read|environment:|secrets\./.test(block)) expect(reaches(graph, job, "invocation-authorization")).toBe(true); for (const job of ["stage", "product-qualification-handoff", "publish-qualified"]) expect(source.indexOf(`  ${job}:`)).toBeGreaterThan(source.indexOf("  validate:")); });
});
