import { createHash } from "node:crypto";
import type { CombinedStaging, PublicComponent } from "./qualification-authoritative-reducer";

export type AuthoritativeProductGateInput = Readonly<{ schemaVersion: 1; kind: "authoritative_product_gate_input"; reducerSha256: string; reducerResult: "success"; candidates: Readonly<Record<PublicComponent, CombinedStaging>> }>;
const fail = (code: string): never => { throw new Error(code); };
export const consumeAuthoritativeReduction = (bytes: Uint8Array): AuthoritativeProductGateInput => {
  let value: unknown; try { value = JSON.parse(Buffer.from(bytes).toString("utf8")); } catch { return fail("AUTHORITATIVE_REDUCER_INVALID"); }
  if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error("AUTHORITATIVE_REDUCER_INVALID"); const objectValue: object = value; const item = Object.fromEntries(Object.entries(objectValue));
  if (JSON.stringify(Object.keys(item).sort()) !== JSON.stringify(["schemaVersion", "kind", "status", "caller", "children", "promotableInput", "retryDispatches", "candidates"].sort()) || item["schemaVersion"] !== 1 || item["kind"] !== "authoritative_product_qualification" || item["status"] !== "satisfied" || item["promotableInput"] !== true || item["retryDispatches"] !== 0) fail("AUTHORITATIVE_REDUCER_DENIED");
  const callerValue = item["caller"]; const childrenValue = item["children"]; if (typeof callerValue !== "object" || callerValue === null || Array.isArray(callerValue) || typeof childrenValue !== "object" || childrenValue === null || Array.isArray(childrenValue)) fail("AUTHORITATIVE_REDUCER_INVALID"); const caller = Object.fromEntries(Object.entries(callerValue)); const children = Object.fromEntries(Object.entries(childrenValue));
  if (JSON.stringify(Object.keys(children).sort()) !== JSON.stringify(["control", "server"]) || ["server", "control"].some((component) => { const child = children[component]; if (typeof child !== "object" || child === null || Array.isArray(child)) return true; const parsed = Object.fromEntries(Object.entries(child)); return parsed["result"] !== "success" || typeof parsed["outputs"] !== "object" || parsed["outputs"] === null; })) fail("AUTHORITATIVE_REDUCER_INVALID");
  const candidateValue = item["candidates"]; if (typeof candidateValue !== "object" || candidateValue === null || Array.isArray(candidateValue)) fail("AUTHORITATIVE_REDUCER_DENIED");
  const candidates = Object.fromEntries(Object.entries(candidateValue)); if (JSON.stringify(Object.keys(candidates).sort()) !== JSON.stringify(["control", "server"]) || ["server", "control"].some((component) => { const candidate = candidates[component]; if (typeof candidate !== "object" || candidate === null || Array.isArray(candidate)) return true; const parsed = Object.fromEntries(Object.entries(candidate)); return parsed["calledJobResult"] !== "success" || parsed["callerRunId"] !== caller["runId"] || parsed["callerRunAttempt"] !== caller["runAttempt"] || parsed["callerRef"] !== caller["ref"] || parsed["callerSha"] !== caller["sha"] || parsed["calledJob"] !== component || parsed["calledWorkflowPath"] !== `.github/workflows/${component}-release.yml`; })) fail("AUTHORITATIVE_REDUCER_INVALID");
  return { schemaVersion: 1, kind: "authoritative_product_gate_input", reducerSha256: createHash("sha256").update(bytes).digest("hex"), reducerResult: "success", candidates: candidates as Record<PublicComponent, CombinedStaging> };
};
