import { createHash } from "node:crypto";
import { inflateRawSync } from "node:zlib";

export type ArtifactKind = "publication-stage" | "staging-binding";
export type ProviderArtifactRecord = Readonly<{ id: string; name: string; digest: string; size: number; createdAt: string; expiresAt: string; expired: false; repository: "furyheimdall/jastreamer"; runId: string; runAttempt: number; headSha: string; archiveSha256: string }>;
export type ProviderArtifactObservation = ProviderArtifactRecord & Readonly<{ component: "server" | "control"; kind: ArtifactKind; entries: Readonly<Record<string, Uint8Array>> }>;
export type ProviderRunContext = Readonly<{ repository: "furyheimdall/jastreamer"; runId: string; runAttempt: number; headSha: string; observedAt: string }>;
export type ProviderApiArtifact = Readonly<{ id: unknown; name: unknown; digest: unknown; size_in_bytes: unknown; created_at: unknown; expires_at: unknown; expired: unknown; workflow_run?: unknown }>;

const fail = (code: string): never => { throw new Error(code); };
const sha256 = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex");
const id = (value: unknown): string => (typeof value === "number" || typeof value === "string") && /^[1-9][0-9]*$/.test(String(value)) ? String(value) : fail("PROVIDER_ARTIFACT_INVALID");
const digest = (value: unknown): string => { if (typeof value !== "string") throw new Error("PROVIDER_ARTIFACT_INVALID"); const normalized = value.replace(/^sha256:/, ""); return /^[0-9a-f]{64}$/.test(normalized) ? normalized : fail("PROVIDER_ARTIFACT_INVALID"); };
const date = (value: unknown): string => typeof value === "string" && Number.isFinite(Date.parse(value)) ? value : fail("PROVIDER_ARTIFACT_INVALID");
const uint16 = (bytes: Uint8Array, offset: number): number => { const low = bytes[offset]; const high = bytes[offset + 1]; if (low === undefined || high === undefined) throw new Error("ARTIFACT_ARCHIVE_INVALID"); return low | (high << 8); };
const uint32 = (bytes: Uint8Array, offset: number): number => (uint16(bytes, offset) | (uint16(bytes, offset + 2) << 16)) >>> 0;
const crcTable = Array.from({ length: 256 }, (_, index) => { let value = index; for (let bit = 0; bit < 8; bit += 1) value = (value & 1) === 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1; return value >>> 0; });
const crc32 = (bytes: Uint8Array): number => { let value = 0xffffffff; for (const byte of bytes) value = (crcTable[(value ^ byte) & 0xff] ?? fail("ARTIFACT_ARCHIVE_INVALID")) ^ (value >>> 8); return (value ^ 0xffffffff) >>> 0; };

export const expectedPublicationFiles = (component: "server" | "control", releaseTag: string): readonly string[] => { const version = releaseTag.slice(`${component}-v`.length); return component === "server" ? [`jastreamer-server_${version}_linux_amd64.deb`, `jastreamer-server_${version}_linux_amd64.rpm`, `jastreamer-server_${version}_linux_arm64.deb`, `jastreamer-server_${version}_linux_arm64.rpm`, `jastreamer-server_${version}_windows_amd64.exe`, `jastreamer-server_${version}_windows_amd64.msi`, `jastreamer-server_${version}_linux_amd64-arm64.oci`] : [`jastreamer-control_${version}_web.zip`, `jastreamer-control_${version}_windows.msix`, `jastreamer-control_${version}_android_universal.apk`]; };
export const expectedProviderArtifactName = (component: "server" | "control", kind: ArtifactKind, runId: string, runAttempt: number): string => kind === "publication-stage" ? `${component}-publication-stage-${runId}-${runAttempt}` : `${component}-publication-staging-binding-${runId}-${runAttempt}`;

export type ZipInspectionLimits = Readonly<{ maxArchiveBytes: number; maxEntries: number; maxEntryBytes: number; maxTotalBytes: number; maxCompressionRatio: number; ratioSlackBytes: number; maxNameBytes: number; maxPathDepth: number }>;
export const DEFAULT_ZIP_LIMITS: ZipInspectionLimits = Object.freeze({ maxArchiveBytes: 512 * 1024 * 1024, maxEntries: 2000, maxEntryBytes: 256 * 1024 * 1024, maxTotalBytes: 1024 * 1024 * 1024, maxCompressionRatio: 100, ratioSlackBytes: 1024 * 1024, maxNameBytes: 512, maxPathDepth: 16 });
const zip64Extra = (bytes: Uint8Array): boolean => { let offset = 0; while (offset < bytes.length) { if (offset + 4 > bytes.length) fail("ARTIFACT_ARCHIVE_INVALID"); const type = uint16(bytes, offset); const size = uint16(bytes, offset + 2); offset += 4; if (offset + size > bytes.length) fail("ARTIFACT_ARCHIVE_INVALID"); if (type === 0x0001) return true; offset += size; } return false; };
const sameBytes = (left: Uint8Array, right: Uint8Array): boolean => left.length === right.length && left.every((byte, index) => byte === right[index]);
const decodeName = (bytes: Uint8Array, utf8: boolean): string => { if (!utf8 && bytes.some((byte) => byte > 0x7f)) fail("ARTIFACT_ARCHIVE_ENTRY_INVALID"); try { return new TextDecoder("utf-8", { fatal: true }).decode(bytes); } catch { return fail("ARTIFACT_ARCHIVE_ENTRY_INVALID"); } };
export type ZipInspectionMetrics = Readonly<{ onInflateBound: (maxOutputLength: number) => void }>;
export const inspectProviderZip = (archive: Uint8Array, limits: ZipInspectionLimits = DEFAULT_ZIP_LIMITS, metrics?: ZipInspectionMetrics): Readonly<Record<string, Uint8Array>> => {
  if (archive.byteLength < 22 || archive.byteLength > limits.maxArchiveBytes) fail("ARTIFACT_ARCHIVE_LIMIT");
  let eocd = -1; for (let offset = archive.byteLength - 22; offset >= Math.max(0, archive.byteLength - 65_557); offset -= 1) if (uint32(archive, offset) === 0x06054b50) { eocd = offset; break; }
  if (eocd < 0 || uint16(archive, eocd + 4) !== 0 || uint16(archive, eocd + 6) !== 0 || uint16(archive, eocd + 8) !== uint16(archive, eocd + 10)) fail("ARTIFACT_ARCHIVE_INVALID");
  const entriesCount = uint16(archive, eocd + 10); const centralSize = uint32(archive, eocd + 12); const centralOffset = uint32(archive, eocd + 16); const commentLength = uint16(archive, eocd + 20);
  if (entriesCount === 0xffff || centralSize === 0xffffffff || centralOffset === 0xffffffff) fail("ARTIFACT_ARCHIVE_INVALID"); if (entriesCount < 1 || entriesCount > limits.maxEntries) fail("ARTIFACT_ARCHIVE_LIMIT"); if (eocd + 22 + commentLength !== archive.byteLength || centralOffset + centralSize !== eocd) fail("ARTIFACT_ARCHIVE_INVALID");
  const entries: Record<string, Uint8Array> = {}; const intervals: Array<readonly [number, number]> = []; let offset = centralOffset; let actualTotal = 0;
  for (let index = 0; index < entriesCount; index += 1) {
    if (offset + 46 > centralOffset + centralSize || uint32(archive, offset) !== 0x02014b50) fail("ARTIFACT_ARCHIVE_INVALID"); const flags = uint16(archive, offset + 8); const method = uint16(archive, offset + 10); const expectedCrc = uint32(archive, offset + 16); const compressedSize = uint32(archive, offset + 20); const declaredSize = uint32(archive, offset + 24); const nameLength = uint16(archive, offset + 28); const extraLength = uint16(archive, offset + 30); const entryCommentLength = uint16(archive, offset + 32); const disk = uint16(archive, offset + 34); const external = uint32(archive, offset + 38); const localOffset = uint32(archive, offset + 42); const centralEnd = offset + 46 + nameLength + extraLength + entryCommentLength;
    if (centralEnd > centralOffset + centralSize || disk !== 0 || compressedSize === 0xffffffff || declaredSize === 0xffffffff || localOffset === 0xffffffff || (flags & ~0x0808) !== 0 || (method !== 0 && method !== 8) || nameLength < 1 || nameLength > limits.maxNameBytes) fail("ARTIFACT_ARCHIVE_INVALID"); const nameBytes = archive.slice(offset + 46, offset + 46 + nameLength); const centralExtra = archive.slice(offset + 46 + nameLength, offset + 46 + nameLength + extraLength); if (zip64Extra(centralExtra)) fail("ARTIFACT_ARCHIVE_INVALID"); const name = decodeName(nameBytes, (flags & 0x0800) !== 0); const parts = name.split("/"); if (name.includes("\\") || name.startsWith("/") || parts.length > limits.maxPathDepth || parts.some((part) => part === "" || part === "." || part === "..") || ((external >>> 16) & 0o170000) === 0o120000 || name in entries) fail("ARTIFACT_ARCHIVE_ENTRY_INVALID"); if (declaredSize > limits.maxEntryBytes || compressedSize > limits.maxArchiveBytes) fail("ARTIFACT_ARCHIVE_LIMIT");
    if (localOffset + 30 > centralOffset || uint32(archive, localOffset) !== 0x04034b50) fail("ARTIFACT_ARCHIVE_INVALID"); const localFlags = uint16(archive, localOffset + 6); const localMethod = uint16(archive, localOffset + 8); const localCrc = uint32(archive, localOffset + 14); const localCompressedSize = uint32(archive, localOffset + 18); const localDeclaredSize = uint32(archive, localOffset + 22); const localNameLength = uint16(archive, localOffset + 26); const localExtraLength = uint16(archive, localOffset + 28); const localHeaderEnd = localOffset + 30 + localNameLength + localExtraLength; if (localHeaderEnd > centralOffset || localFlags !== flags || localMethod !== method || localNameLength !== nameLength || !sameBytes(archive.slice(localOffset + 30, localOffset + 30 + localNameLength), nameBytes) || zip64Extra(archive.slice(localOffset + 30 + localNameLength, localHeaderEnd))) fail("ARTIFACT_ARCHIVE_INVALID"); const descriptor = (flags & 0x0008) !== 0; if ((!descriptor && (localCrc !== expectedCrc || localCompressedSize !== compressedSize || localDeclaredSize !== declaredSize)) || (descriptor && (localCrc !== 0 || localCompressedSize !== 0 || localDeclaredSize !== 0))) fail("ARTIFACT_ARCHIVE_INVALID");
    const dataEnd = localHeaderEnd + compressedSize; if (dataEnd > centralOffset) fail("ARTIFACT_ARCHIVE_INVALID"); let entryEnd = dataEnd; if (descriptor) { const signed = uint32(archive, dataEnd) === 0x08074b50; const descriptorOffset = dataEnd + (signed ? 4 : 0); if (descriptorOffset + 12 > centralOffset || uint32(archive, descriptorOffset) !== expectedCrc || uint32(archive, descriptorOffset + 4) !== compressedSize || uint32(archive, descriptorOffset + 8) !== declaredSize) fail("ARTIFACT_ARCHIVE_INVALID"); entryEnd = descriptorOffset + 12; }
    const compressed = archive.slice(localHeaderEnd, dataEnd); const remaining = limits.maxTotalBytes - actualTotal; const ratioBound = compressedSize * limits.maxCompressionRatio + limits.ratioSlackBytes; const outputBound = Math.min(limits.maxEntryBytes, remaining, ratioBound); if (!Number.isSafeInteger(outputBound) || outputBound < 0) fail("ARTIFACT_ARCHIVE_LIMIT"); let content: Uint8Array; try { if (method === 8) metrics?.onInflateBound(outputBound); content = method === 0 ? compressed : inflateRawSync(compressed, { maxOutputLength: outputBound }); } catch { return fail("ARTIFACT_ARCHIVE_INVALID"); } const actualSize = content.byteLength; if (actualSize > outputBound || actualSize !== declaredSize || crc32(content) !== expectedCrc || actualSize > compressedSize * limits.maxCompressionRatio + limits.ratioSlackBytes) fail("ARTIFACT_ARCHIVE_INVALID"); actualTotal += actualSize; if (actualTotal > limits.maxTotalBytes) fail("ARTIFACT_ARCHIVE_LIMIT"); entries[name] = Uint8Array.from(content); intervals.push([localOffset, entryEnd]); offset = centralEnd;
  }
  if (offset !== centralOffset + centralSize) fail("ARTIFACT_ARCHIVE_INVALID"); intervals.sort((left, right) => left[0] - right[0]); let previousEnd = 0; for (const [start, end] of intervals) { if (start !== previousEnd || end <= start || end > centralOffset) fail("ARTIFACT_ARCHIVE_INVALID"); previousEnd = end; } if (previousEnd !== centralOffset) fail("ARTIFACT_ARCHIVE_INVALID"); return Object.freeze(entries);
};

export type SerializedProviderObservation = Omit<ProviderArtifactObservation, "entries"> & Readonly<{ entryFiles: Readonly<Record<string, Readonly<{ path: string; sha256: string; size: number }>>> }>;
export const serializeProviderObservations = (observations: readonly ProviderArtifactObservation[], write: (relativePath: string, bytes: Uint8Array) => string): readonly SerializedProviderObservation[] => observations.map((observation) => { let expected: readonly string[]; if (observation.kind === "staging-binding") expected = [`${observation.component}-publication-staging.json`]; else { const manifestBytes = observation.entries["qualification/content-manifest.json"] ?? fail("PROVIDER_ARCHIVE_REQUIRED_FILE_MISSING"); let value: unknown; try { value = JSON.parse(Buffer.from(manifestBytes).toString("utf8")); } catch { return fail("PROVIDER_CONTENT_MANIFEST_INVALID"); } if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error("PROVIDER_CONTENT_MANIFEST_INVALID"); const manifest = Object.fromEntries(Object.entries(value)); const tag = manifest["tag"]; if (manifest["component"] !== observation.component || typeof tag !== "string" || !new RegExp(`^${observation.component}-v[0-9]+\\.[0-9]+\\.[0-9]+$`).test(tag)) throw new Error("PROVIDER_CONTENT_MANIFEST_INVALID"); expected = ["qualification/candidate-binding.json", "qualification/content-manifest.json", ...expectedPublicationFiles(observation.component, tag).map((name) => `publication-stage/${name}`)]; } if (JSON.stringify(Object.keys(observation.entries).sort()) !== JSON.stringify([...expected].sort())) fail("PROVIDER_ARCHIVE_INVENTORY_MISMATCH"); const entryFiles: Record<string, { path: string; sha256: string; size: number }> = {}; for (const path of expected) { const bytes = observation.entries[path] ?? fail("PROVIDER_ARCHIVE_REQUIRED_FILE_MISSING"); entryFiles[path] = { path: write(`${observation.component}/${observation.kind}/${path}`, bytes), sha256: sha256(bytes), size: bytes.byteLength }; } const { entries: _entries, ...fields } = observation; return { ...fields, entryFiles }; });

export const observeProviderArtifacts = (context: ProviderRunContext, pages: readonly (readonly ProviderApiArtifact[])[], archives: Readonly<Record<string, Uint8Array>>): readonly ProviderArtifactObservation[] => {
  if (!/^[1-9][0-9]*$/.test(context.runId) || !Number.isSafeInteger(context.runAttempt) || context.runAttempt < 1 || !/^[0-9a-f]{40}$/.test(context.headSha) || !Number.isFinite(Date.parse(context.observedAt))) fail("PROVIDER_RUN_INVALID");
  if (pages.length < 1 || pages.at(-1)?.length === 100 || pages.some((page, index) => index < pages.length - 1 ? page.length !== 100 : page.length > 100)) fail("PROVIDER_PAGINATION_INCOMPLETE"); const records = pages.flat(); const observed: ProviderArtifactObservation[] = [];
  for (const component of ["server", "control"] as const) for (const kind of ["publication-stage", "staging-binding"] as const) {
    const expectedName = expectedProviderArtifactName(component, kind, context.runId, context.runAttempt); const matches = records.filter((record) => record.name === expectedName); if (matches.length !== 1) fail(matches.length === 0 ? "PROVIDER_ARTIFACT_MISSING" : "PROVIDER_ARTIFACT_DUPLICATE"); const raw = matches[0] ?? fail("PROVIDER_ARTIFACT_MISSING");
    const workflowRun = typeof raw.workflow_run === "object" && raw.workflow_run !== null && !Array.isArray(raw.workflow_run) ? Object.fromEntries(Object.entries(raw.workflow_run)) : fail("PROVIDER_ARTIFACT_INVALID"); const artifactId = id(raw.id); const artifactDigest = digest(raw.digest); const rawSize = raw.size_in_bytes;
    if (raw.expired !== false || typeof rawSize !== "number" || !Number.isSafeInteger(rawSize) || rawSize < 1 || workflowRun["id"]?.toString() !== context.runId || workflowRun["run_attempt"] !== context.runAttempt || workflowRun["head_sha"] !== context.headSha || workflowRun["repository"] !== context.repository) throw new Error(raw.expired === true ? "PROVIDER_ARTIFACT_EXPIRED" : "PROVIDER_ARTIFACT_INVALID"); const size: number = rawSize; const createdAt = date(raw.created_at); const expiresAt = date(raw.expires_at); if (Date.parse(createdAt) > Date.parse(context.observedAt) + 300_000 || Date.parse(expiresAt) <= Date.parse(context.observedAt)) fail("PROVIDER_ARTIFACT_STALE"); const archive = archives[artifactId] ?? fail("PROVIDER_ARCHIVE_MISSING"); if (archive.byteLength !== size || sha256(archive) !== artifactDigest) fail("PROVIDER_ARCHIVE_DIGEST_MISMATCH"); const entries = inspectProviderZip(archive);
    const required = kind === "publication-stage" ? [`qualification/candidate-binding.json`, `qualification/content-manifest.json`] : [`${component}-publication-staging.json`]; for (const path of required) if (entries[path] === undefined) fail("PROVIDER_ARCHIVE_REQUIRED_FILE_MISSING"); if (kind === "staging-binding" && Object.keys(entries).length !== 1) fail("PROVIDER_ARCHIVE_EXTRA_FILE"); observed.push({ component, kind, id: artifactId, name: expectedName, digest: artifactDigest, size, createdAt, expiresAt, expired: false, repository: context.repository, runId: context.runId, runAttempt: context.runAttempt, headSha: context.headSha, archiveSha256: sha256(archive), entries });
  }
  const namespace = /^(server|control)-publication-(?:stage|staging-binding)-/; if (records.some((record) => typeof record.name === "string" && namespace.test(record.name) && !observed.some(({ name }) => name === record.name))) fail("PROVIDER_ARTIFACT_COLLISION"); return Object.freeze(observed);
};
