import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { inspectProviderZip } from "./qualification-provider-observer";
import { authorizeK17ProviderInput, authenticateProviderTuple, type K17ProviderAuthorizationInput } from "./provider-observation-contract";

type Item = Record<string, unknown>;
class K17ProviderError extends Error { readonly code: string; constructor(code: string) { super(code); this.code = code; } }
const fail = (code: string): never => { throw new K17ProviderError(code); };
const item = (value: unknown): Item => typeof value === "object" && value !== null && !Array.isArray(value) ? Object.fromEntries(Object.entries(value)) : fail("TASK19_K17_PROVIDER_INPUT_INVALID");
const sha256 = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex"); const denied = (code: string) => ({ schemaVersion: 1, kind: "task19_k17_provider_observation", status: "pending", code, candidateBytesWritten: 0, externalWrites: 0 });
let stagingRoot: string | undefined; let committedRoot: string | undefined;
const main = async (): Promise<void> => {
  const args = process.argv.slice(2); if (args.length !== 6 || args[0] !== "--context" || args[2] !== "--output-root" || args[4] !== "--status") fail("TASK19_K17_PROVIDER_USAGE"); const requested = item(JSON.parse(readFileSync(args[1] ?? fail("TASK19_K17_PROVIDER_USAGE"), "utf8"))); const outputRoot = resolve(args[3] ?? fail("TASK19_K17_PROVIDER_USAGE")); const status = resolve(args[5] ?? fail("TASK19_K17_PROVIDER_USAGE"));
  const text = (name: string): string => typeof requested[name] === "string" ? requested[name] : fail("TASK19_K17_PROVIDER_INPUT_INVALID"); const integer = (name: string): number => typeof requested[name] === "number" && Number.isSafeInteger(requested[name]) ? requested[name] : fail("TASK19_K17_PROVIDER_INPUT_INVALID");
  const protectedInput: K17ProviderAuthorizationInput = { repository: text("repository"), workflowPath: text("workflowPath"), eventName: text("eventName"), runId: text("runId"), runAttempt: integer("runAttempt"), currentSha: text("currentSha"), conclusion: text("conclusion"), artifactId: text("artifactId"), artifactName: text("artifactName"), artifactDigest: text("artifactDigest"), artifactSize: integer("artifactSize"), artifactCreatedAt: text("artifactCreatedAt"), artifactExpiresAt: text("artifactExpiresAt"), qualificationRunId: text("qualificationRunId"), qualificationCurrentSha: text("qualificationCurrentSha") }; const authorized = authorizeK17ProviderInput(protectedInput); const { repository, runId, runAttempt, headSha } = authorized;
  const token = process.env["GITHUB_TOKEN"] ?? fail("TASK19_K17_PROVIDER_ENV_INVALID"); const api = process.env["GITHUB_API_URL"] ?? "https://api.github.com"; const headers = { authorization: `Bearer ${token}`, accept: "application/vnd.github+json", "x-github-api-version": "2022-11-28", "cache-control": "no-cache, no-store", pragma: "no-cache", "user-agent": "jastreamer-task19-k17-provider" }; let providerDate: string | undefined; const get = async (path: string, binary = false): Promise<unknown> => { const response = await fetch(`${api}${path}`, { method: "GET", headers, cache: "no-store", redirect: "follow" }); if (!response.ok) fail("TASK19_K17_PROVIDER_READ_FAILED"); const date = response.headers.get("date"); if (typeof date !== "string" || !Number.isFinite(Date.parse(date))) fail("TASK19_K17_PROVIDER_DATE_INVALID"); providerDate = date ?? fail("TASK19_K17_PROVIDER_DATE_INVALID"); return binary ? new Uint8Array(await response.arrayBuffer()) : response.json(); };
  const repositoryPath = repository.split("/").map(encodeURIComponent).join("/"); const run = item(await get(`/repos/${repositoryPath}/actions/runs/${runId}`));
  const response = item(await get(`/repos/${repositoryPath}/actions/runs/${runId}/artifacts?per_page=100&page=1`)); const values = Array.isArray(response["artifacts"]) ? response["artifacts"].map(item) : fail("TASK19_K17_PROVIDER_PAGINATION_INVALID"); if (response["total_count"] !== values.length || values.length === 100) fail("TASK19_K17_PROVIDER_PAGINATION_INVALID"); const observedAt = providerDate ?? fail("TASK19_K17_PROVIDER_DATE_INVALID"); const artifact = authenticateProviderTuple({ ...authorized, observedAt }, run, values).artifacts[0] ?? fail("TASK19_K17_PROVIDER_MISSING"); const { id, digest, size } = artifact; const archiveValue = await get(`/repos/${repositoryPath}/actions/artifacts/${id}/zip`, true); const archive = archiveValue instanceof Uint8Array ? archiveValue : fail("TASK19_K17_PROVIDER_READ_FAILED"); if (archive.byteLength !== size) fail("TASK19_K17_PROVIDER_SIZE_MISMATCH"); if (sha256(archive) !== digest) fail("TASK19_K17_PROVIDER_DIGEST_MISMATCH"); const entries = inspectProviderZip(archive); if (JSON.stringify(Object.keys(entries)) !== JSON.stringify(["k17-qualification.json"])) fail("TASK19_K17_PROVIDER_INVENTORY_INVALID"); const bytes = entries["k17-qualification.json"] ?? fail("TASK19_K17_PROVIDER_INVENTORY_INVALID"); if (existsSync(outputRoot)) fail("TASK19_K17_PROVIDER_OUTPUT_EXISTS"); const parent = dirname(outputRoot); mkdirSync(parent, { recursive: true, mode: 0o700 }); stagingRoot = mkdtempSync(join(parent, ".task19-k17-")); writeFileSync(join(stagingRoot, "k17-qualification.json"), bytes, { mode: 0o400, flag: "wx" }); renameSync(stagingRoot, outputRoot); stagingRoot = undefined; committedRoot = outputRoot; writeFileSync(status, `${JSON.stringify({ schemaVersion: 1, kind: "task19_k17_provider_observation", status: "observed", authorization: protectedInput, provider: { repository, runId, runAttempt, headSha, artifact }, candidateBytesWritten: bytes.byteLength, externalWrites: 0 }, null, 2)}\n`, { mode: 0o400 }); committedRoot = undefined;
};
try { await main(); } catch (error) { // no-excuse-ok: catch
  if (stagingRoot !== undefined) rmSync(stagingRoot, { recursive: true, force: true }); if (committedRoot !== undefined) rmSync(committedRoot, { recursive: true, force: true }); const code = error instanceof K17ProviderError ? error.code : error instanceof Error && /^[A-Z0-9_]+$/.test(error.message) ? error.message : "TASK19_K17_PROVIDER_FAILED"; const args = process.argv.slice(2); const index = args.indexOf("--status"); const status = index >= 0 ? args[index + 1] : undefined; if (status !== undefined) { const path = resolve(status); mkdirSync(dirname(path), { recursive: true, mode: 0o700 }); writeFileSync(path, `${JSON.stringify(denied(code), null, 2)}\n`, { mode: 0o400 }); } process.stdout.write(`${JSON.stringify(denied(code))}\n`); process.exitCode = 77;
}
