import { createHash } from "node:crypto";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { describe, expect, test } from "bun:test";

const revision = "a".repeat(40); const sha256 = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex");
const crcTable = Array.from({ length: 256 }, (_, index) => { let value = index; for (let bit = 0; bit < 8; bit += 1) value = (value & 1) === 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1; return value >>> 0; });
const crc32 = (bytes: Uint8Array): number => { let value = 0xffffffff; for (const byte of bytes) value = (crcTable[(value ^ byte) & 255] ?? 0) ^ (value >>> 8); return (value ^ 0xffffffff) >>> 0; };
const zip = (entries: Readonly<Record<string, Uint8Array>>): Uint8Array => { const locals: Buffer[] = []; const centrals: Buffer[] = []; let offset = 0; for (const [path, bytes] of Object.entries(entries)) { const name = Buffer.from(path); const local = Buffer.alloc(30); local.writeUInt32LE(0x04034b50); local.writeUInt16LE(20, 4); local.writeUInt32LE(crc32(bytes), 14); local.writeUInt32LE(bytes.length, 18); local.writeUInt32LE(bytes.length, 22); local.writeUInt16LE(name.length, 26); locals.push(local, name, Buffer.from(bytes)); const central = Buffer.alloc(46); central.writeUInt32LE(0x02014b50); central.writeUInt16LE(0x0314, 4); central.writeUInt16LE(20, 6); central.writeUInt32LE(crc32(bytes), 16); central.writeUInt32LE(bytes.length, 20); central.writeUInt32LE(bytes.length, 24); central.writeUInt16LE(name.length, 28); central.writeUInt32LE((0o100644 << 16) >>> 0, 38); central.writeUInt32LE(offset, 42); centrals.push(central, name); offset += local.length + name.length + bytes.length; } const directory = Buffer.concat(centrals); const end = Buffer.alloc(22); end.writeUInt32LE(0x06054b50); end.writeUInt16LE(Object.keys(entries).length, 8); end.writeUInt16LE(Object.keys(entries).length, 10); end.writeUInt32LE(directory.length, 12); end.writeUInt32LE(offset, 16); return Buffer.concat([...locals, directory, end]); };

test("valid Renderer followed by invalid WASAPI leaves no final candidate bytes", async () => {
  const root = mkdtempSync(join(tmpdir(), "task19-physical-atomic-")); const context = join(root, "context.json"); const output = join(root, "physical"); const status = join(root, "status.json"); writeFileSync(context, JSON.stringify({ repository: "furyheimdall/jastreamer", runId: "1001", runAttempt: 2, headSha: revision }));
  const renderer = zip({ "manifest.json": Buffer.from("{}"), "jastreamer-renderer_1.2.3_windows_amd64.msi": Buffer.from("msi") }); const wasapi = zip({ "windows-audio-qualification.json": Buffer.from("{}") });
  const metadata = { created_at: "2026-08-26T11:00:00Z", expires_at: "2026-08-27T12:00:00Z", expired: false, workflow_run: { id: 1001, run_attempt: 2, repository: "furyheimdall/jastreamer", head_sha: revision } }; const artifacts = [{ id: 3001, name: "renderer-candidate-ci", digest: `sha256:${sha256(renderer)}`, size_in_bytes: renderer.length, ...metadata }, { id: 3002, name: "renderer-windows-audio-qualification-physical", digest: `sha256:${sha256(wasapi)}`, size_in_bytes: wasapi.length + 1, ...metadata }];
  const headers = { date: "Tue, 26 Aug 2026 12:00:00 GMT" }; const server = Bun.serve({ port: 0, fetch(request) { const path = new URL(request.url).pathname; if (path.endsWith("/actions/runs/1001")) return Response.json({ id: 1001, run_attempt: 2, head_sha: revision, repository: { full_name: "furyheimdall/jastreamer" }, path: ".github/workflows/renderer-release.yml", event: "workflow_dispatch", conclusion: "success" }, { headers }); if (path.endsWith("/artifacts")) return Response.json({ total_count: artifacts.length, artifacts }, { headers }); if (path.endsWith("/3001/zip")) return new Response(Buffer.from(renderer), { headers }); if (path.endsWith("/3002/zip")) return new Response(Buffer.from(wasapi), { headers }); return new Response("missing", { status: 404, headers }); } });
  try { const child = Bun.spawn(["bun", resolve(import.meta.dirname, "task19-physical-provider-cli.ts"), "--context", context, "--output-root", output, "--status", status], { env: { ...process.env, GITHUB_TOKEN: "test", GITHUB_API_URL: server.url.toString().replace(/\/$/, "") }, stdout: "pipe", stderr: "pipe" }); expect(await child.exited).toBe(77); expect(JSON.parse(readFileSync(status, "utf8"))).toMatchObject({ status: "pending", code: "TASK19_PHYSICAL_PROVIDER_SIZE_MISMATCH", externalWrites: 0 }); expect(existsSync(output)).toBe(false); } finally { server.stop(true); rmSync(root, { recursive: true, force: true }); }
});
