import { createHash } from "node:crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { inspectProviderZip } from "./qualification-provider-observer";
import { authenticateProviderTuple } from "./provider-observation-contract";

type Item = Record<string, unknown>;
class PhysicalProviderError extends Error { readonly code: string; constructor(code: string) { super(code); this.code = code; } }
const fail = (code: string): never => { throw new PhysicalProviderError(code); };
const item = (value: unknown): Item => typeof value === "object" && value !== null && !Array.isArray(value) ? Object.fromEntries(Object.entries(value)) : fail("TASK19_PHYSICAL_PROVIDER_INPUT_INVALID");
const sha256 = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex");
const denied = (code: string) => ({ schemaVersion: 1, kind: "task19_physical_provider_observation", status: "pending", code, candidateBytesWritten: 0, externalWrites: 0 });
let temporaryRoot: string | undefined;

const main = async (): Promise<void> => {
  const args = process.argv.slice(2); if (args.length !== 6 || args[0] !== "--context" || args[2] !== "--output-root" || args[4] !== "--status") fail("TASK19_PHYSICAL_PROVIDER_USAGE");
  const context = item(JSON.parse(readFileSync(args[1] ?? fail("TASK19_PHYSICAL_PROVIDER_USAGE"), "utf8"))); const outputRoot = resolve(args[3] ?? fail("TASK19_PHYSICAL_PROVIDER_USAGE")); const statusPath = resolve(args[5] ?? fail("TASK19_PHYSICAL_PROVIDER_USAGE"));
  const repository = context["repository"] === "furyheimdall/jastreamer" ? context["repository"] : fail("TASK19_PHYSICAL_PROVIDER_INPUT_INVALID"); const runId = typeof context["runId"] === "string" && /^[1-9][0-9]*$/.test(context["runId"]) ? context["runId"] : fail("TASK19_PHYSICAL_PROVIDER_INPUT_INVALID"); const runAttempt = typeof context["runAttempt"] === "number" && Number.isSafeInteger(context["runAttempt"]) && context["runAttempt"] > 0 ? context["runAttempt"] : fail("TASK19_PHYSICAL_PROVIDER_INPUT_INVALID"); const headSha = typeof context["headSha"] === "string" ? context["headSha"] : fail("TASK19_PHYSICAL_PROVIDER_INPUT_INVALID");
  const token = process.env["GITHUB_TOKEN"] ?? fail("TASK19_PHYSICAL_PROVIDER_ENV_INVALID"); const api = process.env["GITHUB_API_URL"] ?? "https://api.github.com"; const headers = { authorization: `Bearer ${token}`, accept: "application/vnd.github+json", "x-github-api-version": "2022-11-28", "cache-control": "no-cache, no-store", pragma: "no-cache", "user-agent": "jastreamer-task19-physical-provider" }; let providerDate: string | undefined;
  const get = async (path: string, binary = false): Promise<unknown> => { const response = await fetch(`${api}${path}`, { method: "GET", headers, cache: "no-store", redirect: "follow" }); if (!response.ok) fail("TASK19_PHYSICAL_PROVIDER_READ_FAILED"); const date = response.headers.get("date"); if (typeof date !== "string" || !Number.isFinite(Date.parse(date))) fail("TASK19_PHYSICAL_PROVIDER_DATE_INVALID"); providerDate = date ?? fail("TASK19_PHYSICAL_PROVIDER_DATE_INVALID"); return binary ? new Uint8Array(await response.arrayBuffer()) : response.json(); };
  const repositoryPath = repository.split("/").map(encodeURIComponent).join("/"); const run = item(await get(`/repos/${repositoryPath}/actions/runs/${runId}`)); const runRepository = item(run["repository"]);
  if (String(run["id"]) !== runId || run["run_attempt"] !== runAttempt || run["head_sha"] !== headSha || runRepository["full_name"] !== repository || run["path"] !== ".github/workflows/renderer-release.yml" || run["event"] !== "workflow_dispatch") fail("TASK19_PHYSICAL_PROVIDER_PROVENANCE_INVALID");
  if (run["conclusion"] !== "success") fail("TASK19_PHYSICAL_PROVIDER_RUN_UNSUCCESSFUL");
  const response = item(await get(`/repos/${repositoryPath}/actions/runs/${runId}/artifacts?per_page=100&page=1`)); const values = Array.isArray(response["artifacts"]) ? response["artifacts"].map(item) : fail("TASK19_PHYSICAL_PROVIDER_PAGINATION_INVALID"); if (response["total_count"] !== values.length || values.length === 100) fail("TASK19_PHYSICAL_PROVIDER_PAGINATION_INVALID");
  const observedAt = providerDate ?? fail("TASK19_PHYSICAL_PROVIDER_DATE_INVALID"); const artifacts = authenticateProviderTuple({ repository, workflowPath: ".github/workflows/renderer-release.yml", eventName: "workflow_dispatch", runId, runAttempt, headSha, observedAt, artifacts: [{ name: "renderer-candidate-ci" }, { name: "renderer-windows-audio-qualification-physical" }] }, run, values).artifacts;
  const entries: Record<string, Uint8Array> = {};
  for (const artifact of artifacts) { const archiveValue = await get(`/repos/${repositoryPath}/actions/artifacts/${artifact.id}/zip`, true); const archive = archiveValue instanceof Uint8Array ? archiveValue : fail("TASK19_PHYSICAL_PROVIDER_READ_FAILED"); if (archive.byteLength !== artifact.size) fail("TASK19_PHYSICAL_PROVIDER_SIZE_MISMATCH"); if (sha256(archive) !== artifact.digest) fail("TASK19_PHYSICAL_PROVIDER_DIGEST_MISMATCH"); for (const [path, bytes] of Object.entries(inspectProviderZip(archive))) { if (entries[path] !== undefined) fail("TASK19_PHYSICAL_PROVIDER_ENTRY_COLLISION"); entries[path] = bytes; } }
  if (entries["manifest.json"] === undefined || !Object.keys(entries).some((path) => /^jastreamer-renderer_[0-9]+\.[0-9]+\.[0-9]+_windows_amd64\.msi$/.test(path)) || entries["windows-audio-qualification.json"] === undefined) fail("TASK19_PHYSICAL_PROVIDER_INVENTORY_INVALID");
  if (existsSync(outputRoot)) fail("TASK19_PHYSICAL_PROVIDER_OUTPUT_EXISTS"); const parent = dirname(outputRoot); mkdirSync(parent, { recursive: true, mode: 0o700 }); temporaryRoot = mkdtempSync(join(parent, ".task19-physical-"), { encoding: "utf8" });
  for (const [path, bytes] of Object.entries(entries)) { const target = join(temporaryRoot, path); mkdirSync(dirname(target), { recursive: true, mode: 0o700 }); writeFileSync(target, bytes, { mode: 0o400, flag: "wx" }); }
  renameSync(temporaryRoot, outputRoot); temporaryRoot = undefined; mkdirSync(dirname(statusPath), { recursive: true, mode: 0o700 }); writeFileSync(statusPath, `${JSON.stringify({ schemaVersion: 1, kind: "task19_physical_provider_observation", status: "observed", repository, runId, runAttempt, headSha, artifacts, candidateBytesWritten: Object.values(entries).reduce((total, bytes) => total + bytes.byteLength, 0), externalWrites: 0 }, null, 2)}\n`, { mode: 0o400 });
};
try { await main(); } catch (error) { // no-excuse-ok: catch
  if (temporaryRoot !== undefined) rmSync(temporaryRoot, { recursive: true, force: true }); const code = error instanceof PhysicalProviderError ? error.code : error instanceof Error && /^[A-Z0-9_]+$/.test(error.message) ? error.message : "TASK19_PHYSICAL_PROVIDER_FAILED"; const args = process.argv.slice(2); const index = args.indexOf("--status"); const status = index >= 0 ? args[index + 1] : undefined; if (status !== undefined) { const path = resolve(status); mkdirSync(dirname(path), { recursive: true, mode: 0o700 }); writeFileSync(path, `${JSON.stringify(denied(code), null, 2)}\n`, { mode: 0o400 }); } process.stdout.write(`${JSON.stringify(denied(code))}\n`); process.exitCode = 77;
}
